# Each prompt/choice group is ordered English, Turkish, Dutch, Arabic.
c='traffic-controllers'
q(c,'s1','An authorised controller clearly tells you to proceed at a red light. What do you do? || Yetkili görevli kırmızı ışıkta size açıkça ilerlemenizi söylüyor. Ne yaparsınız? || Een bevoegde verkeersregelaar geeft bij rood duidelijk aan dat u moet doorrijden. Wat doet u? || يطلب منك منظّم مرور مخوّل بوضوح التقدم رغم الضوء الأحمر. ماذا تفعل؟',
'Follow the instruction carefully | Always wait for green | Ignore the controller | Reverse || Talimata dikkatle uyarsınız | Her durumda yeşili beklersiniz | Görevliyi görmezden gelirsiniz | Geri gidersiniz || Volg de aanwijzing voorzichtig op | Wacht altijd op groen | Negeer de regelaar | Rijd achteruit || تتبع التعليمات بحذر | تنتظر الأخضر دائمًا | تتجاهل المنظّم | ترجع للخلف')
q(c,'s1','A controller is standing nearby but gives no instruction to your traffic stream. What applies? || Görevli yakınınızda duruyor ama sizin trafik akışınıza talimat vermiyor. Ne geçerlidir? || Een regelaar staat in de buurt maar geeft uw verkeersstroom geen aanwijzing. Wat geldt? || يقف منظّم بالقرب منك دون إعطاء تعليمات لاتجاهك. ما الذي يسري؟',
'The applicable lights, signs and rules | All lights become irrelevant | You automatically have priority | All traffic must reverse || Geçerli ışıklar, levhalar ve kurallar | Tüm ışıklar geçersiz olur | Otomatik olarak öncelik kazanırsınız | Herkes geri gitmelidir || De geldende lichten, borden en regels | Alle lichten vervallen | U krijgt automatisch voorrang | Iedereen moet achteruit || الإشارات والقواعد السارية | تصبح كل الأضواء بلا أثر | تحصل تلقائيًا على الأولوية | يجب على الجميع الرجوع')
q(c,'s1','An authorised instruction is unclear. What is the safest response? || Yetkili görevlinin talimatı anlaşılmıyor. En güvenli tepki nedir? || Een bevoegde aanwijzing is onduidelijk. Wat is de veiligste reactie? || تعليمات الشخص المخوّل غير واضحة. ما التصرف الأكثر أمانًا؟',
'Slow down and seek clarification | Guess and accelerate | Ignore every instruction | Swerve immediately || Yavaşlayıp açıklık istersiniz | Tahmin ederek hızlanırsınız | Tüm talimatları yok sayarsınız | Aniden yön değiştirirsiniz || Vertraag en vraag verduidelijking | Raad en versnel | Negeer alle aanwijzingen | Wijk plotseling uit || تخفف السرعة وتطلب التوضيح | تخمّن وتسرع | تتجاهل جميع التعليمات | تنحرف فجأة')
number(c,'s1','Which sign is the official stop signal used by a school traffic warden? || Okul geçidi görevlisinin resmî dur işareti hangi levhadır? || Welk bord is het officiële stopteken van een verkeersbrigadier? || ما رمز إشارة التوقف الرسمية التي يستخدمها مراقب عبور المدارس؟','F10 | B1 | A4 | G1')
q(c,'s2','The lights are completely off. What should you check before applying ordinary priority rules? || Trafik ışıkları tamamen kapalı. Genel öncelik kuralından önce neyi kontrol edersiniz? || De verkeerslichten zijn helemaal uit. Wat controleert u vóór de gewone voorrangsregels? || الأضواء مطفأة تمامًا. ماذا تفحص قبل تطبيق قواعد الأولوية العامة؟',
'Remaining priority signs and road markings | Only the largest vehicle | The colour of other cars | Nothing: signs also stop applying || Geçerli öncelik levhaları ve yol işaretlemeleri | Yalnızca en büyük aracı | Diğer araçların rengini | Hiçbir şeyi; levhalar da geçersizdir || Resterende voorrangsborden en markeringen | Alleen het grootste voertuig | De kleur van andere auto’s | Niets: borden gelden ook niet meer || إشارات الأولوية وعلامات الطريق الباقية | أكبر مركبة فقط | لون السيارات الأخرى | لا شيء، فاللوحات تتوقف أيضًا عن السريان')
number(c,'s2','A fixed sign shows 80 km/h and an electronic panel shows 100 km/h. Which displayed maximum applies? || Sabit levhada 80, elektronik panoda 100 km/sa yazıyor. Hangi üst sınır geçerlidir? || Een vast bord toont 80 km/h en een elektronisch paneel 100 km/h. Welk maximum geldt? || لوحة ثابتة تعرض 80 كم/س ولوحة إلكترونية تعرض 100 كم/س. ما الحد الساري؟','80 km/h | 100 km/h | 90 km/h | 130 km/h')
q(c,'s2','You have a B1 priority-road sign, but your light is red. What must you do? || B1 öncelikli yol levhası var ama ışığınız kırmızı. Ne yapmalısınız? || U rijdt op een voorrangsweg met B1, maar het licht is rood. Wat moet u doen? || أنت على طريق أولوية B1 لكن الضوء أحمر. ماذا يجب أن تفعل؟',
'Stop at the red light | Continue because of B1 | Continue after sounding the horn | Follow the fastest car || Kırmızı ışıkta durmalısınız | B1 nedeniyle geçmelisiniz | Korna çalıp geçmelisiniz | En hızlı aracı takip etmelisiniz || Stop voor rood | Rijd door vanwege B1 | Toeter en rijd door | Volg de snelste auto || تتوقف عند الأحمر | تواصل بسبب B1 | تطلق البوق وتواصل | تتبع أسرع سيارة')
q(c,'s2','A valid 30 km/h sign conflicts with a general default of 50 km/h. What applies? || Geçerli 30 km/sa levhası, genel 50 km/sa sınırıyla çelişiyor. Hangisi geçerlidir? || Een geldig bord van 30 km/h wijkt af van de algemene limiet van 50 km/h. Wat geldt? || لوحة سارية تحدد 30 كم/س بينما الحد العام 50 كم/س. أيهما يسري؟',
'The 30 km/h sign | The 50 km/h default | Their average | Whichever the driver prefers || 30 km/sa levhası | Genel 50 km/sa sınırı | İkisinin ortalaması | Sürücünün tercihi || Het bord van 30 km/h | De algemene 50 km/h | Het gemiddelde | Wat de bestuurder kiest || لوحة 30 كم/س | الحد العام 50 كم/س | متوسط الحدين | ما يفضله السائق')
q(c,'s1','An authorised controller orders you to stop while your light is green. What do you do? || Işık yeşilken yetkili görevli size durmanızı söylüyor. Ne yaparsınız? || Een bevoegde regelaar laat u stoppen terwijl uw licht groen is. Wat doet u? || يأمرك منظّم مخوّل بالتوقف والضوء أخضر. ماذا تفعل؟',
'Stop as instructed | Always continue on green | Speed up | Stop only if another car stops || Talimata uyarak durursunuz | Yeşilde her zaman geçersiniz | Hızlanırsınız | Yalnızca başka araç durursa durursunuz || Stop volgens de aanwijzing | Rijd bij groen altijd door | Versnel | Stop alleen als een andere auto stopt || تتوقف وفق التعليمات | تواصل دائمًا عند الأخضر | تزيد السرعة | تتوقف فقط إذا توقفت سيارة أخرى')

c='special-provisions'
q(c,'s1','When may an individual disability parking card be used? || Kişiye ait engelli park kartı ne zaman kullanılabilir? || Wanneer mag een persoonlijke gehandicaptenparkeerkaart worden gebruikt? || متى يجوز استخدام بطاقة الوقوف الشخصية لذوي الإعاقة؟',
'When parking directly relates to transporting the cardholder | Whenever a relative borrows the car | For any unrelated shopping trip | Only in the cardholder’s own car || Park etme kart sahibinin taşınmasıyla doğrudan ilgiliyse | Bir akraba arabayı ödünç aldığında | Kart sahibiyle ilgisiz her alışverişte | Yalnızca kart sahibinin kendi arabasında || Bij parkeren dat direct verband houdt met vervoer van de kaarthouder | Als een familielid de auto leent | Voor iedere losse boodschap | Alleen in de eigen auto || عندما يرتبط الوقوف مباشرة بنقل صاحب البطاقة | كلما استعار قريب السيارة | لأي تسوق غير مرتبط بصاحبها | فقط في سيارة صاحب البطاقة')
number(c,'s1','Under Article 85, how many hours may a qualifying vehicle park along a broken yellow line with a parking disc? || Madde 85 koşullarını sağlayan araç, park diskiyle kesik sarı çizgi yanında en fazla kaç saat park edebilir? || Hoeveel uur mag een voertuig dat aan artikel 85 voldoet met een parkeerschijf langs een gele onderbroken streep parkeren? || كم ساعة كحد أقصى يجوز لمركبة مستوفية للمادة 85 الوقوف بجانب خط أصفر متقطع مع قرص الوقوف؟','3 | 1 | 2 | 24')
q(c,'s1','Which side of the disability parking card must be readable from outside? || Engelli park kartının hangi yüzü dışarıdan okunabilmelidir? || Welke zijde van de gehandicaptenparkeerkaart moet van buiten leesbaar zijn? || أي وجه من بطاقة الوقوف يجب أن يكون مقروءًا من الخارج؟',
'The front showing its expiry date | Only the photograph side regardless of expiry details | Any side if hidden in the glovebox | Neither side needs to be visible || Son geçerlilik tarihini gösteren ön yüz | Tarihten bağımsız yalnızca fotoğraf yüzü | Torpidodaki herhangi bir yüz | Hiçbir yüzünün görünmesi gerekmez || De voorkant met de vervaldatum | Alleen de fotozijde ongeacht de vervaldatum | Een zijde in het dashboardkastje | Geen zijde hoeft zichtbaar te zijn || الوجه الأمامي الذي يبيّن تاريخ الانتهاء | وجه الصورة فقط دون اعتبار للتاريخ | أي وجه داخل درج السيارة | لا يلزم إظهار أي وجه')
q(c,'s1','Does the disability parking card automatically permit stopping beside a solid yellow line? || Engelli park kartı kesintisiz sarı çizgi yanında durmaya otomatik izin verir mi? || Mag u met de kaart automatisch langs een gele doorgetrokken streep stilstaan? || هل تسمح البطاقة تلقائيًا بالتوقف بجانب خط أصفر متصل؟',
'No, the general no-stopping restriction remains | Yes, for three hours | Yes, without a time limit | Yes, if the engine runs || Hayır, genel durma yasağı sürer | Evet, üç saat | Evet, süresiz | Evet, motor çalışıyorsa || Nee, het algemene stopverbod blijft gelden | Ja, drie uur | Ja, onbeperkt | Ja, met draaiende motor || لا، يبقى منع التوقف العام ساريًا | نعم لثلاث ساعات | نعم بلا حد زمني | نعم إذا كان المحرك يعمل')
q(c,'s1','Does the national disability parking card guarantee free paid parking everywhere? || Ulusal engelli park kartı her yerde ücretsiz park garantisi verir mi? || Garandeert de landelijke kaart overal gratis betaald parkeren? || هل تضمن البطاقة الوطنية الوقوف المجاني في كل موقف مدفوع؟',
'No, check the municipality’s rules | Yes, in every municipality | Yes, only at weekends | Yes, whenever a disc is displayed || Hayır, belediyenin kurallarını kontrol edin | Evet, her belediyede | Evet, yalnızca hafta sonları | Evet, disk gösterildiğinde || Nee, controleer de gemeentelijke regels | Ja, in elke gemeente | Ja, alleen in het weekend | Ja, met een parkeerschijf || لا، افحص قواعد البلدية | نعم في كل البلديات | نعم في العطلات الأسبوعية فقط | نعم عند عرض قرص الوقوف')
q(c,'s1','A disabled parking space is reserved for a specific registration number. May another cardholder use it? || Engelli park yeri belirli bir plakaya ayrılmış. Başka kart sahibi kullanabilir mi? || Een gehandicaptenplaats is voor een bepaald kenteken gereserveerd. Mag een andere kaarthouder er staan? || موقف لذوي الإعاقة مخصص للوحة مركبة محددة. هل يستخدمه صاحب بطاقة أخرى؟',
'No, it remains reserved for that vehicle | Yes, any card overrides the plate | Yes, for three hours | Yes, after sunset || Hayır, o araca ayrılmış olarak kalır | Evet, her kart plakayı geçersiz kılar | Evet, üç saat | Evet, gün batımından sonra || Nee, de plaats blijft voor dat voertuig gereserveerd | Ja, elke kaart gaat boven het kenteken | Ja, drie uur | Ja, na zonsondergang || لا، يبقى مخصصًا لتلك المركبة | نعم أي بطاقة تلغي تخصيص اللوحة | نعم لثلاث ساعات | نعم بعد الغروب')
q(c,'s1','Which card is for transporting eligible residents of a care institution? || Bakım kurumunun uygun koşullardaki sakinlerini taşımak için hangi kart kullanılır? || Welke kaart is voor vervoer van in aanmerking komende bewoners van een zorginstelling? || أي بطاقة مخصصة لنقل المقيمين المؤهلين في مؤسسة رعاية؟',
'Institution card I | Driver card B only | Passenger card P only | A normal parking ticket || Kurum kartı I | Yalnızca sürücü kartı B | Yalnızca yolcu kartı P | Normal park bileti || Instellingskaart I | Alleen bestuurderskaart B | Alleen passagierskaart P | Een normaal parkeerkaartje || بطاقة المؤسسة I | بطاقة السائق B فقط | بطاقة الراكب P فقط | تذكرة وقوف عادية')
q(c,'s1','What is additionally required when using an Article 85 three-hour exemption? || Madde 85 kapsamındaki üç saatlik istisna kullanılırken ayrıca ne gerekir? || Wat is extra nodig bij een vrijstelling van drie uur volgens artikel 85? || ما المطلوب أيضًا عند استخدام استثناء الثلاث ساعات وفق المادة 85؟',
'A visible parking disc showing the start time | Hazard lights throughout | An open bonnet | A note showing departure time only || Başlangıç saatini gösteren görünür park diski | Sürekli dörtlü flaşör | Açık motor kaputu | Yalnızca çıkış saatini gösteren not || Een zichtbare parkeerschijf met de begintijd | Voortdurend alarmlichten | Een open motorkap | Alleen een briefje met de vertrektijd || قرص وقوف ظاهر يبيّن وقت البداية | أضواء تحذير طوال الوقت | غطاء محرك مفتوح | ورقة بوقت المغادرة فقط')
q(c,'s2','Which rules apply in the Netherlands when a foreign disability parking card is legally recognised? || Yabancı engelli park kartı Hollanda’da tanınıyorsa hangi kurallar geçerlidir? || Welke regels gelden bij gebruik van een erkende buitenlandse kaart in Nederland? || أي قواعد تسري عند استخدام بطاقة أجنبية معترف بها في هولندا؟',
'The Dutch conditions and limits | Only the issuing country’s parking rules | No time limits at all | A universal right to park anywhere || Hollanda’nın koşulları ve sınırları | Yalnızca kartı veren ülkenin park kuralları | Hiçbir süre sınırı yoktur | Her yere park etme hakkı || De Nederlandse voorwaarden en grenzen | Alleen de parkeerregels van het land van afgifte | Geen enkele tijdslimiet | Overal vrij parkeren || الشروط والحدود الهولندية | قواعد دولة الإصدار فقط | لا حدود زمنية مطلقًا | حق مطلق في الوقوف في كل مكان')
q(c,'s2','What can allow recognition of a non-EU/EEA card issued by a competent authority? || Yetkili makamın verdiği AB/AEA dışı kartın tanınmasını ne sağlayabilir? || Wat kan erkenning mogelijk maken van een door een bevoegde instantie afgegeven kaart van buiten EU/EER? || ما الذي قد يسمح بالاعتراف ببطاقة من خارج الاتحاد الأوروبي والمنطقة الاقتصادية صادرة عن جهة مختصة؟',
'The prescribed or nearly identical wheelchair symbol on its front | Any blue piece of paper | A handwritten disability note | A foreign number plate alone || Ön yüzündeki belirlenen veya çok benzer tekerlekli sandalye simgesi | Herhangi bir mavi kâğıt | El yazısıyla engellilik notu | Yalnızca yabancı plaka || Het voorgeschreven of vrijwel gelijke rolstoelsymbool op de voorkant | Elk blauw papier | Een handgeschreven briefje | Alleen een buitenlands kenteken || رمز الكرسي المتحرك المحدد أو المشابه جدًا على وجهها | أي ورقة زرقاء | ملاحظة مكتوبة بخط اليد | لوحة مركبة أجنبية فقط')
# Emission zones and the separate oil-supply contingency rule.
c='speed-environmental-zones'
number(c,'s4a','What temporary maximum can Article 86a impose during a serious oil-supply disruption? || Ciddi petrol arzı kesintisinde Madde 86a hangi geçici üst hızı getirebilir? || Welk tijdelijk maximum kan artikel 86a opleggen bij een ernstige verstoring van de olieaanvoer? || ما السرعة القصوى المؤقتة التي تتيحها المادة 86a عند اضطراب خطير في إمدادات النفط؟','90 km/h | 80 km/h | 100 km/h | 130 km/h')
q(c,'s4a','On which roads does the special Article 86a reduction apply? || Madde 86a’nın özel hız indirimi hangi yollarda uygulanır? || Op welke wegen geldt de bijzondere verlaging van artikel 86a? || على أي طرق يسري التخفيض الخاص بالمادة 86a؟',
'Motorways and autowegen | Every street and footpath | Only residential streets | Only bicycle paths || Otoyollar ve autoweg yolları | Her sokak ve yaya yolu | Yalnızca konut sokakları | Yalnızca bisiklet yolları || Autosnelwegen en autowegen | Alle straten en voetpaden | Alleen woonstraten | Alleen fietspaden || الطرق السريعة وطرق autoweg | كل الشوارع وممرات المشاة | الشوارع السكنية فقط | مسارات الدراجات فقط')
q(c,'s4a','Which vehicle is excluded from the special Article 86a reduction? || Hangi araç Madde 86a’nın özel indirim kapsamı dışındadır? || Welk voertuig valt buiten de bijzondere verlaging van artikel 86a? || أي مركبة مستثناة من التخفيض الخاص بالمادة 86a؟',
'A motor vehicle towing a trailer | An ordinary car without a trailer | A T100 bus without a trailer | All passenger cars || Römork çeken motorlu araç | Römorksuz normal otomobil | Römorksuz T100 otobüsü | Tüm otomobiller || Een motorvoertuig met aanhangwagen | Een gewone auto zonder aanhangwagen | Een T100-bus zonder aanhangwagen | Alle personenauto’s || مركبة آلية تجر مقطورة | سيارة عادية دون مقطورة | حافلة T100 دون مقطورة | جميع سيارات الركوب')
q(c,'s4a','Does Article 86a create a permanent ordinary speed limit? || Madde 86a kalıcı ve olağan hız sınırı mı oluşturur? || Stelt artikel 86a een permanente gewone snelheidslimiet in? || هل تضع المادة 86a حدًا عاديًا دائمًا للسرعة؟',
'No, the measure is temporary | Yes, on every Dutch road | Yes, for all vehicles forever | Yes, whenever fuel is expensive || Hayır, tedbir geçicidir | Evet, tüm Hollanda yollarında | Evet, tüm araçlar için süresiz | Evet, yakıt pahalı olduğunda || Nee, de maatregel is tijdelijk | Ja, op alle Nederlandse wegen | Ja, voor alle voertuigen permanent | Ja, zodra brandstof duur is || لا، الإجراء مؤقت | نعم على كل الطرق الهولندية | نعم لكل المركبات إلى الأبد | نعم كلما ارتفع سعر الوقود')
number(c,'s4b','Which main sign marks entry into an emission zone in the chapter’s 2026 system? || Bölümdeki 2026 sisteminde emisyon bölgesine giriş ana levhası hangisidir? || Welk hoofdbord geeft in het beschreven systeem van 2026 het begin van een emissiezone aan? || ما اللوحة الرئيسية لدخول منطقة انبعاثات في نظام 2026 المبيّن بالفصل؟','C22e | C22f | A2 | B1')
number(c,'s4b','Which sign marks the end of an emission-zone restriction? || Emisyon bölgesi kısıtlamasının sonunu hangi levha gösterir? || Welk bord geeft het einde van de emissiezonebeperking aan? || أي لوحة تشير إلى نهاية تقييد منطقة الانبعاثات؟','C22f | C22e | G1 | E1')
q(c,'s4b','Which vehicles does the national zero-emission-zone rule concern? || Ulusal sıfır emisyon bölgesi kuralı hangi araçlarla ilgilidir? || Op welke voertuigen ziet de landelijke zero-emissiezoneregel? || ما المركبات التي تتعلق بها القاعدة الوطنية لمنطقة الانبعاثات الصفرية؟',
'Vans and trucks, subject to transitions and exceptions | All passenger cars and motorcycles | Only bicycles | Only petrol passenger cars || Geçiş hükümleri ve istisnalarla kamyonetler ve kamyonlar | Tüm otomobiller ve motosikletler | Yalnızca bisikletler | Yalnızca benzinli otomobiller || Bestelauto’s en vrachtauto’s, met overgangsregels en uitzonderingen | Alle personenauto’s en motoren | Alleen fietsen | Alleen benzinepersonenauto’s || الشاحنات الصغيرة والكبيرة مع الأحكام الانتقالية والاستثناءات | جميع سيارات الركوب والدراجات النارية | الدراجات الهوائية فقط | سيارات الركوب بالبنزين فقط')
q(c,'s4b','What primarily determines access to a milieuzone for an affected diesel vehicle? || Kapsamdaki dizel aracın milieuzone girişini öncelikle ne belirler? || Wat bepaalt vooral de toegang van een betrokken dieselvoertuig tot een milieuzone? || ما الذي يحدد أساسًا دخول مركبة ديزل مشمولة إلى منطقة منخفضة الانبعاثات؟',
'Its emission class and the vehicle category shown on the plate | Its paint colour | The driver’s age | Whether its windows are open || Emisyon sınıfı ve ek levhada gösterilen araç türü | Boya rengi | Sürücünün yaşı | Camlarının açık olması || De emissieklasse en voertuigcategorie op het onderbord | De lakkleur | De leeftijd van de bestuurder | Of de ramen openstaan || فئة الانبعاثات ونوع المركبة المبين باللوحة الإضافية | لون الطلاء | عمر السائق | فتح النوافذ')
number(c,'s4b','A green milieuzone for diesel cars and vans allows which minimum emission class? || Dizel otomobil ve kamyonetler için yeşil milieuzone en az hangi emisyon sınıfına izin verir? || Welke minimale emissieklasse geldt in een groene milieuzone voor dieselpersonen- en bestelauto’s? || ما أدنى فئة انبعاثات مسموحة لسيارات ومركبات ديزل صغيرة في المنطقة الخضراء؟','4 | 2 | 3 | 6')
number(c,'s4b','A blue milieuzone for diesel cars and vans allows which minimum emission class? || Dizel otomobil ve kamyonetler için mavi milieuzone en az hangi emisyon sınıfına izin verir? || Welke minimale emissieklasse geldt in een blauwe milieuzone voor dieselpersonen- en bestelauto’s? || ما أدنى فئة انبعاثات مسموحة في المنطقة الزرقاء لسيارات ومركبات ديزل صغيرة؟','5 | 3 | 4 | 2')
q(c,'s4b','A zero-emission-zone day exemption is issued for one municipality. Where is it valid? || Bir belediye için sıfır emisyon bölgesi günlük izni verilmiş. Nerede geçerlidir? || Een dagontheffing voor een zero-emissiezone is voor één gemeente afgegeven. Waar geldt die? || صدر إعفاء يومي لمنطقة انبعاثات صفرية لبلدية واحدة. أين يسري؟',
'Only in that municipality | In every Dutch municipality | Throughout the EU | In all neighbouring municipalities || Yalnızca o belediyede | Tüm Hollanda belediyelerinde | AB genelinde | Bütün komşu belediyelerde || Alleen in die gemeente | In alle Nederlandse gemeenten | In de hele EU | In alle buurgemeenten || في تلك البلدية فقط | في جميع البلديات الهولندية | في الاتحاد الأوروبي كله | في كل البلديات المجاورة')
q(c,'s4b','No enforcement camera is visible at a zone boundary. Does the restriction still apply? || Bölge girişinde denetim kamerası görünmüyor. Kısıtlama yine geçerli mi? || Bij de zonegrens is geen camera zichtbaar. Geldt de beperking nog? || لا تظهر كاميرا عند حدود المنطقة. هل يظل التقييد ساريًا؟',
'Yes, it applies at the legally indicated boundary | No, only cameras create the restriction | Only at night | Only if police stop you || Evet, yasal olarak işaretlenen sınırdan itibaren | Hayır, kısıtlamayı yalnızca kamera oluşturur | Yalnızca gece | Yalnızca polis durdurursa || Ja, vanaf de wettelijk aangeduide grens | Nee, alleen camera’s creëren de beperking | Alleen ’s nachts | Alleen als de politie u stopt || نعم من الحد المحدد قانونًا | لا، الكاميرات وحدها تنشئ التقييد | ليلًا فقط | فقط إذا أوقفتك الشرطة')

c='exemptions-waivers'
q(c,'s1','What does an individual ontheffing allow? || Bireysel ontheffing neye izin verir? || Wat staat een individuele ontheffing toe? || بماذا يسمح الإعفاء الفردي ontheffing؟',
'Departure only within the decision’s specified scope | Ignoring every traffic rule | Automatic priority everywhere | Unlimited use by anyone || Yalnızca kararda belirtilen kapsamda kuraldan ayrılmaya | Tüm trafik kurallarını yok saymaya | Her yerde otomatik önceliğe | Herkesin sınırsız kullanımına || Afwijken alleen binnen de vastgelegde reikwijdte | Alle verkeersregels negeren | Overal automatische voorrang | Onbeperkt gebruik door iedereen || مخالفة محددة فقط ضمن نطاق القرار | تجاهل جميع قواعد المرور | أولوية تلقائية في كل مكان | استخدام غير محدود للجميع')
q(c,'s1','Are conditions attached to an exemption legally binding? || Muafiyete eklenen koşullar hukuken bağlayıcı mıdır? || Zijn aan een ontheffing verbonden voorwaarden juridisch bindend? || هل الشروط الملحقة بالإعفاء ملزمة قانونًا؟',
'Yes, breaching them is prohibited | No, they are suggestions | Only on weekdays | Only if printed in red || Evet, ihlal edilmeleri yasaktır | Hayır, tavsiyedir | Yalnızca hafta içi | Yalnızca kırmızı yazılmışsa || Ja, handelen in strijd ermee is verboden | Nee, het zijn adviezen | Alleen op werkdagen | Alleen als ze rood zijn gedrukt || نعم، مخالفتها ممنوعة | لا، هي توصيات | في أيام العمل فقط | فقط إذا طُبعت بالأحمر')
q(c,'s1','Does every Article 87 exemption have to be carried on paper under one universal RVV rule? || Tek bir genel RVV kuralı, her Madde 87 muafiyetini kâğıt olarak taşımayı zorunlu kılar mı? || Moet elke artikel 87-ontheffing volgens één algemene RVV-regel op papier worden meegenomen? || هل توجد قاعدة RVV عامة تلزم بحمل كل إعفاء من المادة 87 ورقيًا؟',
'No, follow the particular exemption’s requirements | Yes, always | Only blue paper is valid | A photograph always replaces every requirement || Hayır, ilgili muafiyetin koşullarını izleyin | Evet, daima | Yalnızca mavi kâğıt geçerlidir | Fotoğraf her koşulun yerine geçer || Nee, volg de eisen van de betreffende ontheffing | Ja, altijd | Alleen blauw papier is geldig | Een foto vervangt altijd alle eisen || لا، اتبع متطلبات الإعفاء المحدد | نعم دائمًا | الورق الأزرق فقط صالح | الصورة تستبدل جميع المتطلبات دائمًا')
q(c,'s1','What is a vrijstelling, as distinguished from an individual ontheffing? || Bireysel ontheffing’den farklı olarak vrijstelling nedir? || Wat is een vrijstelling, anders dan een individuele ontheffing? || ما معنى vrijstelling بخلاف الإعفاء الفردي ontheffing؟',
'A general legal exemption for a defined category | A personal decision in every case | A driver’s informal permission | A parking receipt || Belirli bir kategori için kanuni genel istisna | Her durumda kişisel karar | Sürücünün gayriresmî izni | Park makbuzu || Een algemene wettelijke uitzondering voor een bepaalde categorie | Altijd een persoonlijk besluit | Informele toestemming van een bestuurder | Een parkeerbon || استثناء قانوني عام لفئة محددة | قرار شخصي في كل حالة | إذن غير رسمي من السائق | إيصال وقوف')
number(c,'s2','Which organisation grants medical seatbelt exemptions? || Tıbbi emniyet kemeri muafiyetini hangi kurum verir? || Welke organisatie verleent medische gordelontheffingen? || أي جهة تمنح الإعفاء الطبي من حزام الأمان؟','CBR | RDW | APK | ANPR')
number(c,'s2','What is the maximum stated validity, in years, for the Article 88 medical exemption? || Madde 88 tıbbi muafiyetinin belirtilen geçerliliği en fazla kaç yıldır? || Wat is de maximale vastgestelde geldigheid in jaren van de medische ontheffing van artikel 88? || ما أقصى مدة صلاحية محددة بالسنوات للإعفاء الطبي وفق المادة 88؟','20 | 5 | 10 | 30')
q(c,'s2','A courier frequently gets in and out of the vehicle. Is the courier automatically exempt from wearing a seatbelt? || Kurye araca sık sık binip iniyor. Otomatik kemer muafiyeti var mı? || Een koerier stapt vaak in en uit. Is die automatisch vrijgesteld van de gordel? || يصعد ساعي توصيل إلى المركبة وينزل كثيرًا. هل يُعفى تلقائيًا من الحزام؟',
'No, work alone is not a universal automatic exemption | Yes, every courier is exempt | Yes, if paid hourly | Yes, in every van || Hayır, iş tek başına genel otomatik muafiyet değildir | Evet, tüm kuryeler muaftır | Evet, saatlik ücret alıyorsa | Evet, her kamyonette || Nee, werk alleen geeft geen algemene automatische vrijstelling | Ja, elke koerier is vrijgesteld | Ja, bij uurloon | Ja, in elke bestelauto || لا، العمل وحده ليس إعفاءً تلقائيًا عامًا | نعم كل سعاة التوصيل معفون | نعم إذا تقاضى أجرًا بالساعة | نعم في كل شاحنة صغيرة')
q(c,'s3','What is the current status of RVV Articles 89 and 90 in this chapter? || Bu bölümde RVV 89 ve 90. maddelerinin güncel durumu nedir? || Wat is volgens dit hoofdstuk de huidige status van RVV-artikelen 89 en 90? || ما الوضع الحالي للمادتين 89 و90 من RVV في هذا الفصل؟',
'Both are repealed | Both give unlimited event exemptions | Both regulate motorway speeds | Both create universal doctor priority || İkisi de yürürlükten kaldırılmıştır | İkisi de sınırsız etkinlik muafiyeti verir | İkisi de otoyol hızını düzenler | İkisi de doktorlara genel öncelik verir || Beide zijn vervallen | Beide geven onbeperkte evenementenontheffingen | Beide regelen snelwegsnelheden | Beide geven artsen algemene voorrang || أُلغيتا كلتاهما | تمنحان إعفاءات فعاليات بلا حدود | تنظمان سرعة الطرق السريعة | تمنحان الأطباء أولوية عامة')
q(c,'s5','Which signals together identify a priority vehicle on an urgent task? || Acil görevdeki geçiş üstünlüklü aracı birlikte hangi sinyaller tanımlar? || Welke signalen samen kenmerken een voorrangsvoertuig bij een dringende taak? || ما الإشارتان اللتان تميزان معًا مركبة أولوية في مهمة عاجلة؟',
'Prescribed blue signal and two-tone horn | Blue light alone | Green light alone | Amber light and headlights || Öngörülen mavi ışık ve iki tonlu siren | Yalnızca mavi ışık | Yalnızca yeşil ışık | Sarı ışık ve farlar || Voorgeschreven blauw licht en tweetonige hoorn | Alleen blauw licht | Alleen groen licht | Oranje licht en koplampen || الضوء الأزرق المقرر والمنبّه ثنائي النغمة | الضوء الأزرق وحده | الضوء الأخضر وحده | ضوء أصفر ومصابيح أمامية')
q(c,'s5','How far does Article 91 allow a priority-vehicle driver to depart from RVV rules? || Madde 91 geçiş üstünlüklü araç sürücüsünün RVV’den ne ölçüde ayrılmasına izin verir? || Hoe ver mag een bestuurder van een voorrangsvoertuig volgens artikel 91 van het RVV afwijken? || إلى أي حد تسمح المادة 91 لسائق مركبة أولوية بالخروج عن RVV؟',
'Only as far as the task requires | Without any safety limits | Whenever off duty | Only to park for shopping || Yalnızca görevin gerektirdiği ölçüde | Hiçbir güvenlik sınırı olmadan | Görev dışındayken de her zaman | Yalnızca alışveriş için park ederken || Alleen voor zover de taak dat vereist | Zonder veiligheidsgrenzen | Ook altijd buiten dienst | Alleen bij parkeren om te winkelen || فقط بقدر ما تتطلبه المهمة | دون أي حدود سلامة | دائمًا خارج الخدمة | فقط للوقوف للتسوق')
q(c,'s5','Does an approaching ambulance give ordinary drivers the same Article 91 exemption? || Yaklaşan ambulans normal sürücülere aynı Madde 91 muafiyetini verir mi? || Krijgen gewone bestuurders door een naderende ambulance dezelfde artikel 91-vrijstelling? || هل تمنح سيارة إسعاف مقتربة السائقين العاديين نفس إعفاء المادة 91؟',
'No, make room in the safest lawful way | Yes, run any red light | Yes, all prohibitions disappear | Only if you follow closely behind it || Hayır, güvenli ve yasal şekilde yol açın | Evet, her kırmızıdan geçin | Evet, tüm yasaklar kalkar | Yalnızca ambulansı yakından izlerseniz || Nee, maak veilig en rechtmatig ruimte | Ja, rijd door elk rood licht | Ja, alle verboden vervallen | Alleen als u er vlak achter rijdt || لا، أفسح الطريق بأكثر الطرق أمانًا وقانونية | نعم، تجاوز أي ضوء أحمر | نعم، تزول كل المحظورات | فقط إذا تبعتها عن قرب')
q(c,'s5','What does a green beacon identify on a stationary emergency-service vehicle? || Duran acil hizmet aracındaki yeşil ışık neyi belirtir? || Wat betekent groen licht op een stilstaand hulpverleningsvoertuig? || ماذا يحدد الضوء الأخضر على مركبة طوارئ متوقفة؟',
'The highest-ranking incident commander’s vehicle | A doctor’s universal priority | A vehicle that may ignore all rules | A taxi available for hire || Olay yerindeki en üst yetkili komutanın aracını | Doktorun genel geçiş üstünlüğünü | Her kuralı yok sayabilen aracı | Kiralanabilir taksiyi || Het voertuig van de hoogste incidentcommandant | Algemene voorrang voor een arts | Een voertuig dat alle regels mag negeren | Een beschikbare taxi || مركبة أعلى قائد للحادث رتبة | أولوية عامة لطبيب | مركبة تتجاهل كل القواعد | سيارة أجرة متاحة')
c='driving-skills-road-safety'
q(c,'s-braking','What makes up total stopping distance? || Toplam durma mesafesi nelerden oluşur? || Waaruit bestaat de totale stopafstand? || مم تتكون مسافة التوقف الكلية؟',
'Reaction distance plus braking distance | Braking distance only | Following distance minus speed | Reaction time alone || Tepki mesafesi ve fren mesafesi | Yalnızca fren mesafesi | Takip mesafesi eksi hız | Yalnızca tepki süresi || Reactieafstand plus remweg | Alleen remweg | Volgafstand min snelheid | Alleen reactietijd || مسافة رد الفعل ومسافة الفرملة | مسافة الفرملة وحدها | مسافة المتابعة ناقص السرعة | زمن الاستجابة وحده')
number(c,'s-braking','At 100 km/h, approximately how many metres do you travel in one second before braking starts? || 100 km/sa hızla fren başlamadan bir saniyede yaklaşık kaç metre gidersiniz? || Hoeveel meter legt u bij 100 km/h ongeveer af in één seconde vóór het remmen? || عند 100 كم/س، كم مترًا تقطع تقريبًا خلال ثانية قبل بدء الفرملة؟','28 | 10 | 50 | 100')
number(c,'s-braking','Under similar conditions, doubling speed multiplies braking distance by approximately what factor? || Benzer koşullarda hız iki katına çıktığında fren mesafesi yaklaşık kaç katına çıkar? || Met ongeveer welke factor neemt de remweg toe als de snelheid onder gelijke omstandigheden verdubbelt? || في ظروف متماثلة، بماذا تتضاعف مسافة الفرملة تقريبًا عند مضاعفة السرعة؟','4 | 2 | 3 | 8')
q(c,'s-following','What is the two-second following rule? || İki saniyelik takip kuralı nedir? || Wat is de tweesecondenregel? || ما قاعدة الثانيتين للمتابعة؟',
'A practical starting point in good conditions, not a fixed statutory minimum | A guarantee in ice and fog | A legal maximum gap | A rule only for trucks || İyi koşullarda pratik başlangıç ölçüsü; sabit kanuni asgari değildir | Buz ve siste garanti | Yasal azami takip aralığı | Yalnızca kamyon kuralı || Een praktisch uitgangspunt bij goede omstandigheden, geen vast wettelijk minimum | Een garantie bij ijs en mist | Een wettelijk maximuminterval | Alleen een regel voor vrachtauto’s || نقطة بداية عملية في ظروف جيدة وليست حدًا قانونيًا أدنى ثابتًا | ضمان على الجليد والضباب | أقصى فاصل قانوني | قاعدة للشاحنات فقط')
q(c,'s-following','Why leave extra distance behind a large truck? || Büyük kamyonun arkasında neden daha fazla mesafe bırakılır? || Waarom houdt u achter een grote vrachtauto extra afstand? || لماذا تترك مسافة إضافية خلف شاحنة كبيرة؟',
'To improve the view ahead and gain reaction time | To prevent the truck from turning | To avoid using headlights | To make overtaking compulsory || İleriyi daha iyi görmek ve tepki süresi kazanmak için | Kamyonun dönmesini engellemek için | Far kullanmamak için | Sollamayı zorunlu kılmak için || Voor beter zicht vooruit en meer reactietijd | Om te verhinderen dat de vrachtauto afslaat | Om geen verlichting te gebruiken | Om inhalen verplicht te maken || لتحسين الرؤية أمامك وكسب زمن للاستجابة | لمنع الشاحنة من الانعطاف | للاستغناء عن المصابيح | لجعل التجاوز إلزاميًا')
q(c,'s-visibility','The posted limit is higher than the speed at which you can stop within the visible clear road. What should you do? || Levhadaki hız, görünen boş yolda durabileceğiniz hızdan yüksek. Ne yapmalısınız? || De aangegeven limiet is hoger dan de snelheid waarbij u binnen het zichtbare vrije stuk kunt stoppen. Wat doet u? || الحد المعلن أعلى من السرعة التي تستطيع عندها التوقف ضمن الطريق المرئي الخالي. ماذا تفعل؟',
'Reduce speed below the posted maximum | Maintain the posted maximum | Accelerate through the poor visibility | Rely on the vehicle behind || Levhadaki üst sınırın altına yavaşlayın | Levhadaki azami hızı koruyun | Görüşsüz alanda hızlanın | Arkadaki araca güvenin || Verlaag de snelheid onder het aangegeven maximum | Houd het maximum aan | Versnel bij slecht zicht | Vertrouw op het voertuig achter u || تخفض السرعة دون الحد المعلن | تحافظ على الحد المعلن | تسرع خلال ضعف الرؤية | تعتمد على المركبة خلفك')
q(c,'s-skidding','During an emergency stop in an ABS-equipped car, how should you brake? || ABS’li otomobilde acil duruş sırasında nasıl fren yapmalısınız? || Hoe remt u bij een noodstop met ABS? || كيف تفرمل في توقف طارئ بسيارة مزودة بـABS؟',
'Press firmly and continuously; steer as needed | Pump the pedal repeatedly | Release whenever the pedal vibrates | Use only the parking brake || Pedala kuvvetle ve sürekli basın; gerektiğinde yön verin | Pedalı tekrar tekrar pompalayın | Pedal titreşince bırakın | Yalnızca park frenini kullanın || Druk stevig en aanhoudend; stuur indien nodig | Pomp herhaaldelijk | Laat los zodra het pedaal trilt | Gebruik alleen de parkeerrem || تضغط بقوة وباستمرار وتوجّه حسب الحاجة | تضخ الدواسة مرارًا | تتركها كلما اهتزت | تستخدم فرامل الوقوف فقط')
q(c,'s-skidding','What is the main advantage of ABS? || ABS’nin başlıca yararı nedir? || Wat is het belangrijkste voordeel van ABS? || ما الفائدة الأساسية لنظام ABS؟',
'Preventing sustained wheel lock to retain steering control | Guaranteeing the shortest stop on every surface | Removing all skid risk | Increasing permitted speed || Sürekli tekerlek kilitlenmesini önleyerek direksiyon kontrolünü korumak | Her zeminde en kısa duruşu garanti etmek | Tüm kayma riskini kaldırmak | İzin verilen hızı artırmak || Langdurig blokkeren voorkomen om bestuurbaarheid te behouden | Op elk oppervlak de kortste stop garanderen | Elk sliprisico wegnemen | De toegestane snelheid verhogen || منع انغلاق العجلات المستمر للحفاظ على التوجيه | ضمان أقصر توقف على كل سطح | إزالة كل خطر انزلاق | زيادة السرعة المسموحة')
q(c,'s-skidding','How should you prepare to enter a slippery bend? || Kaygan viraja girmeden nasıl hazırlanmalısınız? || Hoe bereidt u zich voor op een gladde bocht? || كيف تستعد لدخول منعطف زلق؟',
'Reduce speed before the bend and use smooth inputs | Accelerate sharply into it | Brake abruptly halfway through | Make sudden steering changes || Virajdan önce yavaşlayıp kumandaları yumuşak kullanın | Girerken sert hızlanın | Ortasında aniden frenleyin | Direksiyonu ani çevirin || Vertraag vóór de bocht en bedien soepel | Versnel krachtig bij het insturen | Rem halverwege plotseling | Stuur abrupt || تخفف السرعة قبل المنعطف وتستخدم حركات سلسة | تسرع بقوة عند دخوله | تفرمل فجأة في منتصفه | تغيّر التوجيه فجأة')
q(c,'s-fatigue','You keep yawning, drift in your lane and struggle to stay awake. What should you do? || Sürekli esniyor, şeritte kayıyor ve uyanık kalmakta zorlanıyorsunuz. Ne yapmalısınız? || U gaapt, slingert en kunt moeilijk wakker blijven. Wat doet u? || تتثاءب وتنحرف داخل المسار وتجد صعوبة في البقاء يقظًا. ماذا تفعل؟',
'Stop somewhere safe and rest | Turn up music and continue | Open a window and keep driving | Drive faster to finish sooner || Güvenli yerde durup dinlenin | Müziği açıp devam edin | Camı açıp sürün | Çabuk bitirmek için hızlanın || Stop veilig en rust | Zet muziek harder en rijd door | Open een raam en rijd door | Rijd sneller om eerder aan te komen || تتوقف في مكان آمن وتستريح | ترفع صوت الموسيقى وتواصل | تفتح النافذة وتواصل | تسرع لتصل مبكرًا')
q(c,'s-fatigue','Can caffeine replace the sleep a very tired driver needs? || Kafein çok yorgun sürücünün ihtiyaç duyduğu uykunun yerini tutar mı? || Kan cafeïne de slaap vervangen die een erg vermoeide bestuurder nodig heeft? || هل يعوض الكافيين النوم الذي يحتاجه سائق شديد التعب؟',
'No, any temporary help is not a substitute for sleep | Yes, indefinitely | Yes, if windows are open | Yes, on motorways only || Hayır, geçici etkisi uykunun yerine geçmez | Evet, süresiz | Evet, camlar açıksa | Evet, yalnızca otoyolda || Nee, tijdelijke hulp vervangt slaap niet | Ja, onbeperkt | Ja, met open ramen | Ja, alleen op snelwegen || لا، المساعدة المؤقتة لا تعوض النوم | نعم إلى أجل غير محدد | نعم مع نوافذ مفتوحة | نعم على الطرق السريعة فقط')
number(c,'s-vehicle','What minimum main-groove tyre tread depth does the chapter give for passenger cars? || Bölüm, otomobil lastiklerinin ana olukları için hangi asgari diş derinliğini verir? || Welke minimale profieldiepte in de hoofdgroeven geldt volgens het hoofdstuk voor personenauto’s? || ما أدنى عمق لأخاديد الإطارات الرئيسية لسيارات الركوب المذكور في الفصل؟','1.6 mm | 0.8 mm | 1.0 mm | 3.0 mm')
q(c,'s-vehicle','Your car passed APK recently but now has a serious brake fault. What does the inspection prove? || Otomobil yakın zamanda APK’den geçti ama şimdi ciddi fren arızası var. Muayene neyi kanıtlar? || Uw auto is net APK-goedgekeurd maar heeft nu een ernstig remdefect. Wat bewijst de keuring? || اجتازت سيارتك فحص APK مؤخرًا لكن ظهر عيب خطير بالفرامل. ماذا يثبت الفحص؟',
'It does not guarantee present roadworthiness; repair the fault | It guarantees safe use until the next APK | The fault may be ignored for a year | Only the tyre condition matters || Şu an güvenli olduğunu garanti etmez; arızayı giderin | Sonraki APK’ye kadar güvenliği garanti eder | Arıza bir yıl yok sayılabilir | Yalnızca lastik durumu önemlidir || Geen garantie voor huidige veiligheid; herstel het defect | Veiligheid tot de volgende APK is gegarandeerd | Het defect mag een jaar worden genegeerd | Alleen banden zijn van belang || لا يضمن السلامة الحالية؛ أصلح العيب | يضمن السلامة حتى الفحص التالي | يمكن تجاهل العيب لسنة | حالة الإطارات وحدها مهمة')
q(c,'s-environment','Your tyres begin aquaplaning. What is the recommended response? || Lastikler su üzerinde kaymaya başladı. Önerilen tepki nedir? || Uw banden krijgen aquaplaning. Wat is de aanbevolen reactie? || بدأت الإطارات تطفو على الماء. ما التصرف الموصى به؟',
'Ease off the accelerator smoothly and avoid abrupt braking or steering | Brake sharply and steer sharply | Accelerate harder | Pull the parking brake immediately || Gazı yumuşak bırakıp ani fren ve direksiyondan kaçının | Sert frenleyip sert yön verin | Daha fazla gaz verin | Hemen park frenini çekin || Laat het gas soepel los en vermijd abrupt remmen of sturen | Rem en stuur hard | Geef meer gas | Trek direct de parkeerrem aan || ترفع قدمك عن الوقود تدريجيًا وتتجنب الفرملة والتوجيه المفاجئ | تفرمل وتنعطف بقوة | تزيد التسارع | تسحب فرامل الوقوف فورًا')
q(c,'s-environment','Are winter tyres legally compulsory in the Netherlands according to this chapter? || Bu bölüme göre Hollanda’da kış lastiği yasal olarak zorunlu mu? || Zijn winterbanden volgens dit hoofdstuk wettelijk verplicht in Nederland? || هل إطارات الشتاء إلزامية قانونًا في هولندا وفق هذا الفصل؟',
'No, although they can improve winter grip | Yes, all year | Yes, from October for every vehicle | Only if the vehicle is red || Hayır, ancak kışın tutunmayı iyileştirebilir | Evet, yıl boyunca | Evet, ekimden itibaren tüm araçlarda | Yalnızca araç kırmızıysa || Nee, maar ze kunnen wintergrip verbeteren | Ja, het hele jaar | Ja, vanaf oktober voor elk voertuig | Alleen bij een rode auto || لا، لكنها قد تحسن التماسك شتاءً | نعم طوال العام | نعم من أكتوبر لكل المركبات | فقط للمركبات الحمراء')
q(c,'s-environment','Where should you anticipate sudden crosswind gusts? || Ani yan rüzgâr darbelerini nerelerde beklemelisiniz? || Waar moet u plotselinge zijwindvlagen verwachten? || أين تتوقع هبات جانبية مفاجئة؟',
'On bridges, in open areas and when passing large vehicles | Only in closed garages | Only while parked | Only on windless days || Köprülerde, açık alanlarda ve büyük araçları geçerken | Yalnızca kapalı garajlarda | Yalnızca park halindeyken | Yalnızca rüzgârsız günlerde || Op bruggen, open plekken en bij het passeren van grote voertuigen | Alleen in gesloten garages | Alleen bij parkeren | Alleen op windstille dagen || على الجسور والمناطق المكشوفة وعند تجاوز مركبات كبيرة | في المرائب المغلقة فقط | أثناء الوقوف فقط | في الأيام بلا رياح فقط')

c='road-traffic-act'
number(c,'s-alcohol','What blood-alcohol limit applies to an experienced driver? || Deneyimli sürücü için kandaki alkol sınırı nedir? || Welke alcohollimiet in het bloed geldt voor een ervaren bestuurder? || ما حد الكحول في الدم للسائق المتمرس؟','0.5 ‰ | 0.2 ‰ | 0.8 ‰ | 1.3 ‰')
number(c,'s-alcohol','What blood-alcohol limit applies to a beginner driver? || Acemi sürücü için kandaki alkol sınırı nedir? || Welke alcohollimiet in het bloed geldt voor een beginnend bestuurder? || ما حد الكحول في الدم للسائق المبتدئ؟','0.2 ‰ | 0.5 ‰ | 0.8 ‰ | 1.0 ‰')
q(c,'s-alcohol','Does having a prescription automatically exempt a driver from impairment rules? || Reçete sahibi olmak sürücüyü etkilenmiş halde sürüş kurallarından otomatik muaf tutar mı? || Geeft een recept automatisch vrijstelling van regels over rijden onder invloed? || هل تمنح الوصفة الطبية إعفاءً تلقائيًا من قواعد القيادة تحت التأثير؟',
'No; medicines can impair driving and legal rules still apply | Yes, every prescribed medicine is safe | Yes, if taken at home | Only if the packaging is kept || Hayır; ilaçlar sürüşü etkileyebilir ve kurallar geçerlidir | Evet, her reçeteli ilaç güvenlidir | Evet, evde alınırsa | Yalnızca ambalaj saklanırsa || Nee; medicijnen kunnen rijvaardigheid beïnvloeden en de regels blijven gelden | Ja, elk voorgeschreven middel is veilig | Ja, bij inname thuis | Alleen als de verpakking wordt bewaard || لا؛ قد تؤثر الأدوية وتبقى القواعد سارية | نعم كل دواء موصوف آمن | نعم إذا أُخذ في المنزل | فقط عند الاحتفاظ بالعبوة')
q(c,'s-alcohol','How are combined alcohol/drug use limits treated compared with single-substance limits? || Alkol ve uyuşturucunun birlikte kullanım sınırları tek maddeye göre nasıldır? || Hoe worden combinatiegrenzen voor alcohol/drugs behandeld ten opzichte van afzonderlijk gebruik? || كيف تُعامل حدود الجمع بين الكحول والمخدرات مقارنة باستخدام مادة واحدة؟',
'Substantially lower combination limits apply | Combining substances raises the limits | Only the strongest substance counts | No rules apply when combined || Çok daha düşük birlikte kullanım sınırları uygulanır | Birleştirmek sınırları yükseltir | Yalnızca en güçlü madde sayılır | Birlikte kullanımda kural yoktur || Er gelden aanzienlijk lagere combinatiegrenzen | Combineren verhoogt de grenzen | Alleen de sterkste stof telt | Bij combineren gelden geen regels || تسري حدود أقل بكثير للاستخدام المشترك | الجمع يرفع الحدود | تُحسب المادة الأقوى فقط | لا قواعد عند الجمع')
q(c,'s-licence','Where do you apply for the Dutch driving-licence document after passing? || Sınavdan sonra Hollanda ehliyet belgesi için nereye başvurursunuz? || Waar vraagt u na het slagen het Nederlandse rijbewijsdocument aan? || أين تطلب وثيقة رخصة القيادة الهولندية بعد النجاح؟',
'The municipality | The driving school | A fuel station | The insurer || Belediyeye | Sürücü kursuna | Akaryakıt istasyonuna | Sigortacıya || Bij de gemeente | Bij de rijschool | Bij een tankstation | Bij de verzekeraar || لدى البلدية | لدى مدرسة القيادة | في محطة وقود | لدى شركة التأمين')
number(c,'s-licence','Which organisation conducts driving tests and assesses driving fitness? || Sürüş sınavlarını ve sürüşe uygunluk değerlendirmesini hangi kurum yapar? || Welke organisatie neemt rijexamens af en beoordeelt rijgeschiktheid? || أي جهة تجري اختبارات القيادة وتقيّم اللياقة للقيادة؟','CBR | RDW | ANPR | APK')
number(c,'s-licence','What is the category B vehicle maximum authorised mass stated in the chapter? || Bölümde B sınıfı araç için belirtilen azami izin verilen kütle nedir? || Welke toegestane maximummassa noemt het hoofdstuk voor een voertuig van categorie B? || ما الكتلة القصوى المسموحة لمركبة الفئة B المذكورة بالفصل؟','3500 kg | 4250 kg | 7500 kg | 12000 kg')
number(c,'s-licence','What maximum authorised combination mass does B+ code 96 permit? || B+ kod 96 araç birleşimi için hangi azami izin verilen kütleyi sağlar? || Welke toegestane maximummassa van de combinatie staat B+ code 96 toe? || ما أقصى كتلة مسموحة للمجموعة مع B+ الرمز 96؟','4250 kg | 3500 kg | 7500 kg | 12000 kg')
q(c,'s-licence','With category B, when may a trailer over 750 kg be towed under the rule described here? || Buradaki kurala göre B sınıfıyla 750 kg üzeri römork ne zaman çekilebilir? || Wanneer mag u met B volgens deze regel een aanhangwagen boven 750 kg trekken? || متى يجوز بالفئة B جر مقطورة تزيد على 750 كغ وفق القاعدة هنا؟',
'When the combined authorised maximum mass does not exceed 3500 kg | Whenever the trailer is empty | Whenever the route is short | When the driver is over 30 || Birleşimin izin verilen azami kütlesi 3500 kg’ı aşmıyorsa | Römork her boş olduğunda | Yol her kısa olduğunda | Sürücü 30 yaş üzerindeyse || Als de gezamenlijke toegestane maximummassa niet boven 3500 kg komt | Altijd als de aanhangwagen leeg is | Bij elke korte rit | Als de bestuurder ouder dan 30 is || عندما لا تتجاوز الكتلة القصوى المسموحة للمجموعة 3500 كغ | كلما كانت المقطورة فارغة | كلما كان الطريق قصيرًا | إذا تجاوز السائق 30 عامًا')
q(c,'s-licence','A 17-year-old has passed the B test. Where may they drive under 2toDrive before turning 18? || B sınavını geçen 17 yaşındaki kişi 18’den önce 2toDrive ile nerede sürebilir? || Waar mag een 17-jarige na het B-examen tot 18 jaar onder 2toDrive rijden? || أين يقود من نجح بفحص B وعمره 17 سنة وفق 2toDrive قبل بلوغ 18؟',
'Only in the Netherlands with the required coach and pass | Alone throughout the EU | Alone in the Netherlands | Anywhere with any adult || Gerekli rehber ve belgeyle yalnızca Hollanda’da | AB genelinde tek başına | Hollanda’da tek başına | Herhangi bir yetişkinle her yerde || Alleen in Nederland met de vereiste coach en pas | Alleen in de hele EU | Alleen in Nederland | Overal met een willekeurige volwassene || في هولندا فقط مع المشرف والتصريح المطلوبين | منفردًا في كل الاتحاد الأوروبي | منفردًا في هولندا | في كل مكان مع أي بالغ')
number(c,'s-licence','What is the general maximum validity in years of an ordinary B licence, before age or medical exceptions? || Yaş veya tıbbi istisnalar dışında normal B ehliyetinin genel azami geçerliliği kaç yıldır? || Wat is de algemene maximale geldigheid in jaren van een B-rijbewijs vóór leeftijds- of medische uitzonderingen? || ما الصلاحية القصوى العامة بالسنوات لرخصة B قبل استثناءات العمر أو الصحة؟','10 | 5 | 15 | 20')
q(c,'s-penalty','Who decides after police licence surrender whether it is retained or returned under Article 164? || Madde 164 kapsamında polis ehliyeti aldıktan sonra tutulmasına veya iadesine kim karar verir? || Wie beslist na invordering door de politie over inhouding of teruggave volgens artikel 164? || من يقرر بعد سحب الشرطة للرخصة الاحتفاظ بها أو إعادتها وفق المادة 164؟',
'The public prosecutor | The driving instructor | The insurer | The CBR automatically in every case || Savcı | Sürüş eğitmeni | Sigortacı | Her durumda otomatik olarak CBR || De officier van justitie | De rijinstructeur | De verzekeraar | Altijd automatisch het CBR || المدعي العام | مدرب القيادة | شركة التأمين | CBR تلقائيًا في كل حالة')
q(c,'s-penalty','A WAHV fine and a CBR fitness measure arise from one incident. Are they the same legal procedure? || Aynı olaydan WAHV cezası ve CBR uygunluk tedbiri doğuyor. Aynı hukuki süreç mi? || Een WAHV-boete en CBR-maatregel volgen uit één incident. Zijn dat dezelfde procedures? || نتجت غرامة WAHV وتدبير لياقة من CBR عن واقعة واحدة. هل هما الإجراء نفسه؟',
'No, they are distinct legal mechanisms | Yes, always one procedure | CBR measures cancel every fine | Fines automatically cancel all medical checks || Hayır, ayrı hukuki mekanizmalardır | Evet, daima tek süreç | CBR her cezayı iptal eder | Ceza tüm tıbbi kontrolleri iptal eder || Nee, het zijn verschillende juridische mechanismen | Ja, altijd één procedure | CBR-maatregelen schrappen elke boete | Boetes schrappen alle medische controles || لا، هما آليتان قانونيتان منفصلتان | نعم دائمًا إجراء واحد | تدابير CBR تلغي كل الغرامات | الغرامات تلغي كل الفحوص الطبية')
q(c,'s-fitness','Your health changes and you are unsure whether driving is safe. What does the chapter advise? || Sağlığınız değişti ve güvenli sürüşten emin değilsiniz. Bölüm ne öneriyor? || Uw gezondheid verandert en u twijfelt of rijden veilig is. Wat adviseert het hoofdstuk? || تغيرت صحتك وأنت غير متأكد من سلامة القيادة. بماذا ينصح الفصل؟',
'Discuss the effect with your doctor; a Health Declaration can enable CBR assessment | Keep driving regardless of symptoms | Every condition is automatically reported by your car | A licence guarantees fitness forever || Etkisini doktorla görüşün; Sağlık Beyanı CBR değerlendirmesini sağlayabilir | Belirtilere bakmadan devam edin | Araç her hastalığı otomatik bildirir | Ehliyet ömür boyu uygunluk garantisidir || Bespreek dit met uw arts; een Gezondheidsverklaring kan CBR-beoordeling mogelijk maken | Rijd door ongeacht klachten | Uw auto meldt elke aandoening automatisch | Een rijbewijs garandeert levenslange geschiktheid || ناقش الأثر مع طبيبك؛ يمكن للإقرار الصحي إتاحة تقييم CBR | واصل مهما كانت الأعراض | سيارتك تبلغ عن كل مرض تلقائيًا | الرخصة تضمن اللياقة إلى الأبد')
q(c,'s-beginner','How long can beginner-driver status last, depending on first licence and age? || İlk ehliyet ve yaşa bağlı olarak acemi sürücülük ne kadar sürebilir? || Hoe lang kan de beginnersperiode duren, afhankelijk van eerste rijbewijs en leeftijd? || كم قد تستمر صفة السائق المبتدئ حسب أول رخصة والعمر؟',
'Five or seven years | Always two years | Always ten years | Until the first fine || Beş veya yedi yıl | Her zaman iki yıl | Her zaman on yıl | İlk cezaya kadar || Vijf of zeven jaar | Altijd twee jaar | Altijd tien jaar | Tot de eerste boete || خمس أو سبع سنوات | سنتان دائمًا | عشر سنوات دائمًا | حتى أول غرامة')
number(c,'s-beginner','After how many registered beginner penalty points for qualifying serious offences is the driver reported to the CBR? || Koşulları sağlayan ciddi ihlallerde kaç kayıtlı acemi ceza puanından sonra sürücü CBR’ye bildirilir? || Na hoeveel geregistreerde beginnerspunten voor kwalificerende ernstige feiten wordt de bestuurder bij het CBR gemeld? || بعد كم نقطة مسجلة للمبتدئ عن مخالفات جسيمة مؤهلة يُبلّغ CBR بالسائق؟','2 | 1 | 5 | 10')
c='traffic-signs-theory'
q(c,'s1','What can a supplementary plate beneath a sign do? || Levhanın altındaki ek levha ne yapabilir? || Wat kan een onderbord bij een verkeersbord doen? || ماذا يمكن أن تفعل لوحة إضافية أسفل إشارة؟',
'Clarify or limit how the sign applies | Automatically cancel every nearby sign | Replace all traffic lights | Give every driver priority || Levhanın kapsamını açıklayabilir veya sınırlayabilir | Yakındaki her levhayı otomatik iptal edebilir | Tüm trafik ışıklarının yerine geçebilir | Her sürücüye öncelik verebilir || De werking verduidelijken of beperken | Elk bord in de buurt automatisch opheffen | Alle verkeerslichten vervangen | Elke bestuurder voorrang geven || توضح أو تحدد نطاق سريان الإشارة | تلغي كل إشارة قريبة تلقائيًا | تستبدل جميع الأضواء | تمنح كل سائق الأولوية')
q(c,'s2','What is the important difference between B6 and B7? || B6 ile B7 arasındaki önemli fark nedir? || Wat is het belangrijke verschil tussen B6 en B7? || ما الفرق المهم بين B6 وB7؟',
'B7 requires a complete stop; B6 requires giving way without an automatic stop | B6 always requires stopping but B7 never does | Both are advisory only | Both give priority || B7 tam duruş ister; B6 her durumda durmadan yol vermeyi gerektirir | B6 daima durdurur, B7 hiç durdurmaz | İkisi de yalnızca tavsiyedir | İkisi de öncelik verir || B7 verplicht volledig stoppen; B6 verplicht voorrang verlenen zonder altijd te stoppen | B6 verplicht altijd stoppen en B7 nooit | Beide zijn alleen advies | Beide geven voorrang || B7 يوجب التوقف الكامل؛ B6 يوجب إعطاء الأولوية دون توقف إلزامي دائمًا | B6 يوجب التوقف دائمًا وB7 لا | كلاهما توصية فقط | كلاهما يمنح الأولوية')
number(c,'s2','Which sign indicates an advisory speed rather than a mandatory maximum? || Zorunlu üst sınır yerine tavsiye edilen hızı hangi levha belirtir? || Welk bord geeft een adviessnelheid in plaats van een verplicht maximum aan? || أي إشارة تعني سرعة استرشادية لا حدًا أقصى إلزاميًا؟','A4 | A1 | A3 | B7')
q(c,'s2','What should you do after an A2 end-of-speed-limit sign? || A2 hız sınırı sonu levhasından sonra ne yapmalısınız? || Wat doet u na bord A2, einde maximumsnelheid? || ماذا تفعل بعد إشارة A2 لنهاية حد السرعة؟',
'Determine the limit from road type and other applicable signs | Always accelerate to 130 km/h | Assume all speed rules end | Always drive at 50 km/h || Yol türü ve diğer geçerli işaretlerden sınırı belirleyin | Her zaman 130 km/sa’ya çıkın | Tüm hız kurallarının bittiğini varsayın | Her zaman 50 km/sa sürün || Bepaal de limiet uit het wegtype en andere geldende borden | Versnel altijd naar 130 km/h | Neem aan dat alle snelheidsregels eindigen | Rijd altijd 50 km/h || تحدد الحد من نوع الطريق والإشارات الأخرى السارية | تسرع دائمًا إلى 130 كم/س | تفترض انتهاء كل قواعد السرعة | تقود دائمًا بسرعة 50 كم/س')
q(c,'s2','What is the main purpose of a category J warning sign? || J kategorisi uyarı levhasının temel amacı nedir? || Wat is het hoofddoel van een waarschuwingsbord uit categorie J? || ما الغرض الأساسي من إشارة تحذير من الفئة J؟',
'Warn of a hazard so you can prepare | Automatically give you priority | Always prohibit entry | Cancel a red light || Hazırlanmanız için tehlikeyi haber vermek | Size otomatik öncelik vermek | Her zaman girişi yasaklamak | Kırmızı ışığı iptal etmek || Waarschuwen voor gevaar zodat u zich voorbereidt | Automatisch voorrang geven | Altijd de toegang verbieden | Rood licht opheffen || التحذير من خطر للاستعداد له | منحك الأولوية تلقائيًا | منع الدخول دائمًا | إلغاء الضوء الأحمر')
q(c,'s3','A traffic light turns yellow and you can stop safely. What must you do? || Işık sarıya döndü ve güvenle durabilirsiniz. Ne yapmalısınız? || Het verkeerslicht wordt geel en u kunt veilig stoppen. Wat moet u doen? || تحول الضوء إلى الأصفر ويمكنك التوقف بأمان. ماذا يجب أن تفعل؟',
'Stop | Accelerate | Continue because yellow is optional | Use the horn and continue || Durmalısınız | Hızlanmalısınız | Sarı isteğe bağlı olduğu için geçmelisiniz | Korna çalıp geçmelisiniz || Stoppen | Versnellen | Doorrijden omdat geel vrijblijvend is | Toeteren en doorrijden || تتوقف | تسرع | تواصل لأن الأصفر اختياري | تطلق البوق وتواصل')
q(c,'s3','What does a green arrow traffic light apply to? || Yeşil oklu trafik ışığı ne için geçerlidir? || Waarvoor geldt een groene pijl in een verkeerslicht? || على ماذا ينطبق الضوء الأخضر على شكل سهم؟',
'Only the direction shown by the arrow | Every direction | Only pedestrians | Only reversing vehicles || Yalnızca okun gösterdiği yön | Bütün yönler | Yalnızca yayalar | Yalnızca geri giden araçlar || Alleen de richting van de pijl | Alle richtingen | Alleen voetgangers | Alleen achteruitrijdende voertuigen || اتجاه السهم فقط | جميع الاتجاهات | المشاة فقط | المركبات التي ترجع فقط')
q(c,'s3','What does a flashing yellow traffic light mean? || Yanıp sönen sarı trafik ışığı ne anlama gelir? || Wat betekent een geel knipperend verkeerslicht? || ماذا يعني ضوء أصفر وامض؟',
'Danger: proceed with care under applicable rules | You have unconditional priority | All vehicles must park | The road is permanently closed || Tehlike; geçerli kurallara göre dikkatle hareket edin | Koşulsuz önceliğiniz var | Tüm araçlar park etmeli | Yol kalıcı olarak kapalı || Gevaar: wees voorzichtig en volg geldende regels | U hebt onvoorwaardelijk voorrang | Alle voertuigen moeten parkeren | De weg is permanent gesloten || خطر: انتبه واتبع القواعد السارية | لديك أولوية مطلقة | يجب أن تتوقف كل المركبات للوقوف | الطريق مغلق دائمًا')
q(c,'s3','A matrix signal shows a red cross over your lane. What does it mean? || Şeridinizin üzerinde elektronik kırmızı çarpı var. Anlamı nedir? || Een matrixsignaal toont een rood kruis boven uw rijstrook. Wat betekent dit? || تظهر علامة حمراء متقاطعة فوق مسارك. ماذا تعني؟',
'The lane is closed | The lane is only for overtaking | You must speed up | Only lorries may use it || Şerit kapalıdır | Şerit yalnızca sollama içindir | Hızlanmalısınız | Yalnızca kamyonlar kullanabilir || De rijstrook is gesloten | Alleen inhalen toegestaan | U moet versnellen | Alleen vrachtauto’s mogen er rijden || المسار مغلق | المسار للتجاوز فقط | يجب أن تزيد السرعة | تستخدمه الشاحنات فقط')
q(c,'s4','A broken white line is on your side of a combined solid/broken marking. May you cross it? || Birleşik kesintisiz/kesik çizgide sizin tarafınız kesik. Geçebilir misiniz? || Bij een combinatie van doorgetrokken en onderbroken strepen ligt de onderbroken streep aan uw kant. Mag u oversteken? || في خط مزدوج متصل ومتقطع، المتقطع على جانبك. هل تعبره؟',
'Yes, if the manoeuvre is otherwise permitted and safe | Never | Always, without checking | Only while reversing || Evet, manevra başka bakımdan da izinli ve güvenliyse | Asla | Kontrol etmeden her zaman | Yalnızca geri giderken || Ja, als de manoeuvre verder toegestaan en veilig is | Nooit | Altijd, zonder te kijken | Alleen achteruit || نعم إذا كانت المناورة مسموحة وآمنة من الجوانب الأخرى | أبدًا | دائمًا دون فحص | عند الرجوع فقط')
q(c,'s4','What do shark’s teeth road markings indicate? || Köpekbalığı dişi yol işaretleri neyi belirtir? || Wat geven haaientanden op het wegdek aan? || ماذا تعني علامات أسنان القرش على الطريق؟',
'A duty to give way | A parking space | A mandatory speed increase | An end of all restrictions || Yol verme yükümlülüğü | Park yeri | Zorunlu hız artırma | Tüm kısıtlamaların sonu || Een voorrangsplicht | Een parkeerplaats | Verplicht versnellen | Einde van alle beperkingen || وجوب إعطاء الأولوية | مكان وقوف | زيادة سرعة إلزامية | نهاية كل القيود')
q(c,'s4','Does a bicycle crossing marking alone determine cyclists’ priority? || Bisiklet geçidi işareti tek başına bisikletlinin önceliğini belirler mi? || Bepaalt alleen de markering van een fietsoversteek de voorrang? || هل تحدد علامة معبر الدراجات وحدها أولوية الدراجين؟',
'No, check signs, shark’s teeth and ordinary rules | Yes, cyclists always go first | Yes, cars always go first | Only the colour of the bicycle matters || Hayır; levhaları, dişleri ve genel kuralları kontrol edin | Evet, bisikletli daima önce geçer | Evet, otomobil daima önce geçer | Yalnızca bisikletin rengi önemlidir || Nee, controleer borden, haaientanden en gewone regels | Ja, fietsers gaan altijd eerst | Ja, auto’s gaan altijd eerst | Alleen de fietskleur telt || لا، افحص الإشارات وأسنان القرش والقواعد العامة | نعم الدراجون أولًا دائمًا | نعم السيارات أولًا دائمًا | لون الدراجة وحده مهم')
q(c,'s4','What does an arrow painted in your lane indicate? || Şeridinize çizilmiş ok neyi belirtir? || Wat geeft een pijl op uw rijstrook aan? || ماذا يحدد السهم المرسوم في مسارك؟',
'The permitted direction or directions for that lane | The wind direction | A suggested parking angle | An optional decoration || Şeridin izin verilen yönünü veya yönlerini | Rüzgârın yönünü | Önerilen park açısını | İsteğe bağlı süsü || De toegestane richting of richtingen van die strook | De windrichting | Een parkeerhoekadvies | Vrijblijvende versiering || الاتجاه أو الاتجاهات المسموحة للمسار | اتجاه الرياح | زاوية وقوف مقترحة | زخرفة اختيارية')
q(c,'s4','A speed number is painted on the road without an A1 sign. What does the chapter say? || Yolda A1 levhası olmadan hız rakamı boyalı. Bölüm ne diyor? || Een snelheid staat op het wegdek zonder A1-bord. Wat zegt het hoofdstuk? || رقم سرعة مرسوم على الطريق دون لوحة A1. ماذا يقول الفصل؟',
'A painted number alone is not the same as an A1 maximum-speed sign | Every painted number always overrides every sign | It cancels speed limits | It permits that speed in all conditions || Boyalı rakam tek başına A1 azami hız levhasıyla aynı değildir | Her boyalı rakam her levhayı geçersiz kılar | Hız sınırlarını kaldırır | Her koşulda o hıza izin verir || Een geschilderd getal alleen is niet hetzelfde als een A1-bord | Elk getal gaat boven elk bord | Het heft snelheidslimieten op | Het staat die snelheid altijd toe || الرقم المرسوم وحده ليس مثل لوحة A1 للسرعة القصوى | كل رقم مرسوم يعلو على كل لوحة | يلغي حدود السرعة | يسمح بتلك السرعة في كل الظروف')
c='traffic-rules'
q(c,'s1','What is the normal road-position rule for drivers? || Sürücüler için normal yol konumu kuralı nedir? || Wat is de normale plaats-op-de-wegregel voor bestuurders? || ما القاعدة العادية لموضع السائق على الطريق؟',
'Keep as far right as possible unless another rule applies | Always drive in the middle | Always drive on the left | Use the pavement whenever convenient || Başka kural yoksa mümkün olduğunca sağda kalın | Daima ortada sürün | Daima solda sürün | Uygun olduğunda kaldırımı kullanın || Houd zoveel mogelijk rechts tenzij een andere regel geldt | Rijd altijd in het midden | Rijd altijd links | Gebruik het trottoir als dat uitkomt || الزم أقصى اليمين الممكن ما لم تنطبق قاعدة أخرى | قد دائمًا في الوسط | قد دائمًا يسارًا | استخدم الرصيف متى ناسبك')
q(c,'s1','Where should a pedestrian walk when a pavement or footpath is available? || Kaldırım veya yaya yolu varsa yaya nerede yürümelidir? || Waar loopt een voetganger als een trottoir of voetpad aanwezig is? || أين يسير المشاة عند وجود رصيف أو ممر مشاة؟',
'On the pavement or footpath | In the middle of the carriageway | On the cycle path first | Always on the verge || Kaldırımda veya yaya yolunda | Taşıt yolunun ortasında | Öncelikle bisiklet yolunda | Daima bankette || Op het trottoir of voetpad | Midden op de rijbaan | Eerst op het fietspad | Altijd in de berm || على الرصيف أو ممر المشاة | وسط مسار المركبات | على مسار الدراجات أولًا | على الحافة دائمًا')
q(c,'s2','The driver ahead has moved left and signals a left turn. On which side do you pass when safe? || Öndeki sürücü sola yanaşıp sol sinyal verdi. Güvenliyse hangi taraftan geçersiniz? || Uw voorganger is links voorgesorteerd en geeft links richting aan. Aan welke kant passeert u veilig? || تموضع السائق أمامك يسارًا وأشار للانعطاف يسارًا. من أي جانب تتجاوزه عندما يكون آمنًا؟',
'On the right | Only on the left | On the pavement | On either side without checking || Sağdan | Yalnızca soldan | Kaldırımdan | Kontrol etmeden iki taraftan da || Rechts | Alleen links | Via het trottoir | Zonder kijken aan beide kanten || من اليمين | من اليسار فقط | عبر الرصيف | من أي جانب دون فحص')
q(c,'s2','May you overtake a vehicle immediately before or on a zebra crossing? || Yaya geçidinin hemen önünde veya üzerinde araç sollayabilir misiniz? || Mag u een voertuig vlak vóór of op een zebrapad inhalen? || هل يجوز تجاوز مركبة مباشرة قبل معبر المشاة أو عليه؟',
'No | Yes, if you indicate | Yes, if it is slow | Only on the right || Hayır | Evet, sinyal verirseniz | Evet, yavaşsa | Yalnızca sağdan || Nee | Ja, met richtingaanwijzer | Ja, als het langzaam rijdt | Alleen rechts || لا | نعم إذا أشرت | نعم إذا كانت بطيئة | من اليمين فقط')
q(c,'s3','In slow-moving queues in the same direction, may a queue on the right pass the queue on the left? || Aynı yöndeki yavaş trafik kuyruklarında sağ sıra sol sırayı geçebilir mi? || Mag in langzaam rijdende files in dezelfde richting de rechterfile de linker passeren? || في طوابير بطيئة بالاتجاه نفسه، هل يتجاوز الطابور الأيمن الأيسر؟',
'Yes, this is an exception to normal overtaking | No, never | Only bicycles may | Only at night || Evet, normal sollama kuralının istisnasıdır | Hayır, asla | Yalnızca bisikletler | Yalnızca gece || Ja, dit is een uitzondering op normaal inhalen | Nee, nooit | Alleen fietsen | Alleen ’s nachts || نعم، هذا استثناء من قاعدة التجاوز العادية | لا أبدًا | الدراجات فقط | ليلًا فقط')
q(c,'s4','The exit of an intersection is blocked by a queue. What should you do before entering? || Kavşak çıkışı kuyruk nedeniyle kapalı. Girmeden ne yapmalısınız? || De uitgang van een kruispunt is door een file geblokkeerd. Wat doet u vóór het oprijden? || مخرج التقاطع مسدود بطابور. ماذا تفعل قبل دخوله؟',
'Wait until you can clear it completely | Enter and wait in the middle | Sound the horn and enter | Follow the nearest car closely || Tamamen geçebileceğiniz zamana kadar bekleyin | Girip ortada bekleyin | Korna çalıp girin | En yakın aracı yakından izleyin || Wacht tot u het geheel kunt vrijmaken | Rijd op en wacht in het midden | Toeter en rijd op | Volg de dichtstbijzijnde auto vlakbij || تنتظر حتى تستطيع إخلاءه بالكامل | تدخل وتنتظر في الوسط | تطلق البوق وتدخل | تتبع أقرب سيارة عن قرب')
q(c,'s5','At an equivalent unregulated paved-road intersection, a car approaches from your right. Who gives way? || Eşdeğer, düzenlenmemiş ve kaplamalı yolların kavşağında sağdan otomobil geliyor. Kim yol verir? || Bij een gelijkwaardig ongeregeld kruispunt van verharde wegen komt een auto van rechts. Wie verleent voorrang? || في تقاطع متكافئ غير منظم لطرق معبدة تأتي سيارة من يمينك. من يعطي الأولوية؟',
'You give way | The other car always gives way | The smaller car gives way | Whoever has fewer passengers gives way || Siz yol verirsiniz | Diğer otomobil daima yol verir | Küçük otomobil yol verir | Az yolcusu olan yol verir || U verleent voorrang | De andere auto altijd | De kleinste auto | Wie minder passagiers heeft || أنت تعطي الأولوية | السيارة الأخرى دائمًا | السيارة الأصغر | من لديه ركاب أقل')
q(c,'s5','At an otherwise unregulated intersection, what is the ordinary rule for a tram approaching from the left? || Başka şekilde düzenlenmemiş kavşakta soldan tramvay gelirse olağan kural nedir? || Wat is bij een verder ongeregeld kruispunt de gewone regel voor een tram van links? || ما القاعدة العادية لترام قادم من اليسار عند تقاطع غير منظم؟',
'Give way to the tram | Cars always go first | The tram gives way because it is on the left | Only buses yield to trams || Tramvaya yol verin | Otomobiller daima önce geçer | Tramvay solda olduğu için yol verir | Yalnızca otobüsler tramvaya yol verir || Verleen voorrang aan de tram | Auto’s gaan altijd eerst | De tram verleent voorrang omdat hij van links komt | Alleen bussen laten trams voor || أعطِ الأولوية للترام | السيارات أولًا دائمًا | يعطي الترام الأولوية لأنه من اليسار | الحافلات فقط تفسح للترام')
q(c,'s7','You turn left while an oncoming car turns right into the same road. Who should you let go first? || Siz sola, karşıdan gelen otomobil aynı yola sağa dönüyor. Kime önce geçiş verirsiniz? || U slaat linksaf en een tegenligger rechtsaf dezelfde weg in. Wie laat u voorgaan? || تنعطف يسارًا وسيارة مقابلة تنعطف يمينًا إلى الطريق نفسه. من تتركه يمر أولًا؟',
'The oncoming right-turning car | Yourself because the turn is longer | Whoever indicated first | Whoever is faster || Karşıdan sağa dönen otomobile | Dönüşünüz uzun olduğu için kendinize | İlk sinyal verene | Daha hızlı olana || De rechtsafslaande tegenligger | Uzelf omdat uw bocht langer is | Wie het eerst richting aangaf | Wie sneller is || السيارة المقابلة المنعطفة يمينًا | نفسك لأن الانعطاف أطول | من أشار أولًا | الأسرع')
q(c,'s8','You cannot stop within the clear distance you can see, even below the speed limit. What must change? || Sınırın altında olsanız da görünen boş mesafede duramıyorsunuz. Ne değişmeli? || U kunt niet stoppen binnen de zichtbare vrije afstand, ook onder de limiet. Wat moet veranderen? || لا يمكنك التوقف ضمن المسافة المرئية الخالية رغم أنك دون الحد. ما الذي يجب تغييره؟',
'Reduce your speed | Increase your speed | Only switch on the radio | Nothing if below the posted limit || Hızınızı azaltın | Hızınızı artırın | Yalnızca radyoyu açın | Levha sınırı altındaysanız hiçbir şey || Verlaag uw snelheid | Verhoog uw snelheid | Zet alleen de radio aan | Niets als u onder de limiet zit || تخفض سرعتك | تزيد سرعتك | تشغل المذياع فقط | لا شيء ما دمت دون الحد')
q(c,'s9','What does a solid yellow line prohibit? || Kesintisiz sarı çizgi neyi yasaklar? || Wat verbiedt een gele doorgetrokken streep? || ماذا يمنع الخط الأصفر المتصل؟',
'Stopping | Only overnight parking | Only loading | Only parking longer than an hour || Durmayı | Yalnızca gece parkını | Yalnızca yüklemeyi | Yalnızca bir saati aşan parkı || Stilstaan | Alleen nachtelijk parkeren | Alleen laden | Alleen langer dan een uur parkeren || التوقف | الوقوف ليلًا فقط | التحميل فقط | الوقوف لأكثر من ساعة فقط')
q(c,'s10','What does a broken yellow line prohibit? || Kesik sarı çizgi neyi yasaklar? || Wat verbiedt een gele onderbroken streep? || ماذا يمنع الخط الأصفر المتقطع؟',
'Parking | All driving | Every brief passenger drop-off | Only night-time driving || Park etmeyi | Tüm sürüşü | Her kısa yolcu indirmeyi | Yalnızca gece sürüşünü || Parkeren | Al het rijden | Elk kort uitstappen | Alleen ’s nachts rijden || الوقوف | كل قيادة | كل إنزال قصير لراكب | القيادة الليلية فقط')
number(c,'s10','Within how many metres of an intersection is parking prohibited? || Kavşağın kaç metre yakınında park yasaktır? || Binnen hoeveel meter van een kruispunt is parkeren verboden? || ضمن كم متر من التقاطع يُمنع الوقوف؟','5 | 1 | 2 | 20')
q(c,'s12','When may you use the horn? || Kornayı ne zaman kullanabilirsiniz? || Wanneer mag u claxonneren? || متى يجوز استخدام البوق؟',
'To avert imminent danger | To greet friends | To show frustration | To announce every turn || Yakın tehlikeyi önlemek için | Arkadaş selamlamak için | Öfke göstermek için | Her dönüşü bildirmek için || Om dreigend gevaar af te wenden | Om vrienden te groeten | Om ergernis te tonen | Om elke afslag aan te kondigen || لتفادي خطر وشيك | لتحية الأصدقاء | لإظهار الغضب | لإعلان كل انعطاف')
q(c,'s13','Heavy rain alone occurs, without fog or snow. May you use the rear fog light because of that rain? || Sis veya kar yok, yalnızca şiddetli yağmur var. Bu nedenle arka sis lambasını açabilir misiniz? || Er is alleen zware regen, zonder mist of sneeuw. Mag daarom het mistachterlicht aan? || يوجد مطر غزير فقط دون ضباب أو ثلج. هل تشغّل ضوء الضباب الخلفي بسبب المطر؟',
'No | Yes, whenever it rains | Yes, above 50 km/h | Only on motorways || Hayır | Evet, her yağmurda | Evet, 50 km/sa üzerinde | Yalnızca otoyolda || Nee | Ja, bij elke regen | Ja, boven 50 km/h | Alleen op snelwegen || لا | نعم عند كل مطر | نعم فوق 50 كم/س | على الطرق السريعة فقط')
q(c,'s13','Does an amber warning beacon give the vehicle priority? || Sarı uyarı ışığı araca geçiş üstünlüğü verir mi? || Geeft een geel zwaailicht het voertuig voorrang? || هل يمنح ضوء التحذير الأصفر المركبة الأولوية؟',
'No, it warns of a special or dangerous situation | Yes, over everyone | Only at intersections | Only if accompanied by headlights || Hayır, özel veya tehlikeli durumu bildirir | Evet, herkese karşı | Yalnızca kavşakta | Yalnızca farlarla birlikte || Nee, het waarschuwt voor een bijzondere of gevaarlijke situatie | Ja, boven iedereen | Alleen op kruispunten | Alleen samen met koplampen || لا، يحذر من وضع خاص أو خطر | نعم على الجميع | عند التقاطعات فقط | مع المصابيح الأمامية فقط')
number(c,'s16','What minimum construction-related speed capability is specified for motorway access? || Otoyola giriş için yapısal olarak en az hangi hız yeteneği belirtilmiştir? || Welke minimale constructiegerelateerde snelheid geldt voor toegang tot de autosnelweg? || ما أدنى قدرة سرعة تصميمية محددة لدخول الطريق السريع؟','60 km/h | 25 km/h | 45 km/h | 50 km/h')
number(c,'s17','What is the maximum speed in an erf? || Erf içinde azami hız nedir? || Wat is de maximumsnelheid in een erf? || ما السرعة القصوى في منطقة erf؟','15 km/h | 30 km/h | 45 km/h | 50 km/h')
q(c,'s17','Where may you park in an erf? || Erf içinde nerede park edebilirsiniz? || Waar mag u in een erf parkeren? || أين يجوز الوقوف في منطقة erf؟',
'Only in designated marked parking spaces | Anywhere on the shared surface | Across a footpath | Anywhere for less than an hour || Yalnızca belirlenmiş işaretli park yerlerinde | Ortak alanda her yerde | Yaya yolunun üzerinde | Bir saatten azsa her yerde || Alleen op aangewezen gemarkeerde parkeerplaatsen | Overal op het gedeelde wegdek | Dwars op een voetpad | Overal korter dan een uur || في أماكن الوقوف المخصصة والمعلّمة فقط | في أي مكان بالسطح المشترك | عبر ممر المشاة | في أي مكان لأقل من ساعة')
q(c,'s18','What determines priority at a roundabout? || Dönel kavşakta önceliği ne belirler? || Wat bepaalt de voorrang op een rotonde? || ما الذي يحدد الأولوية عند الدوار؟',
'Signs and markings; ordinary rules if none regulate priority | Traffic already inside always has priority | Entering traffic always has priority | The biggest vehicle always has priority || Levha ve işaretler; düzenleme yoksa genel kurallar | İçerideki trafik daima önceliklidir | Giren trafik daima önceliklidir | En büyük araç daima önceliklidir || Borden en markeringen; anders de gewone regels | Verkeer op de rotonde heeft altijd voorrang | Oprijdend verkeer heeft altijd voorrang | Het grootste voertuig heeft altijd voorrang || اللوحات والعلامات وإلا القواعد العامة | المرور داخل الدوار له الأولوية دائمًا | المرور الداخل له الأولوية دائمًا | المركبة الأكبر لها الأولوية دائمًا')
q(c,'s18','What signal should you give before leaving a roundabout? || Dönel kavşaktan çıkmadan hangi sinyali vermelisiniz? || Welke richting geeft u aan vóór het verlaten van een rotonde? || ما الإشارة التي تعطيها قبل الخروج من الدوار؟',
'Right indicator | Left indicator | Hazard lights | No signal in any case || Sağ sinyal | Sol sinyal | Dörtlüler | Hiçbir durumda sinyal yok || Rechts | Links | Alarmlichten | Nooit een signaal || إشارة اليمين | إشارة اليسار | أضواء التحذير | لا إشارة مطلقًا')
q(c,'s19','A pedestrian clearly intends to step onto a zebra crossing. What must you do? || Yaya açıkça geçide adım atmak üzere. Ne yapmalısınız? || Een voetganger wil duidelijk een zebrapad oplopen. Wat doet u? || ينوي مشاة بوضوح الدخول إلى المعبر. ماذا يجب أن تفعل؟',
'Give way | Continue until they reach the middle | Sound the horn and continue | Yield only if they wave || Yol verin | Ortaya gelene kadar devam edin | Korna çalıp geçin | Yalnızca el sallarsa yol verin || Laat voorgaan | Rijd door tot het midden bereikt is | Toeter en rijd door | Alleen voor laten gaan na zwaaien || تفسح له الطريق | تواصل حتى يصل الوسط | تطلق البوق وتواصل | تفسح فقط إذا لوّح')
q(c,'s21','Loose animals are near the road. What is the correct response? || Yol yakınında başıboş hayvanlar var. Doğru tepki nedir? || Er lopen losse dieren bij de weg. Wat is de juiste reactie? || توجد حيوانات طليقة قرب الطريق. ما التصرف الصحيح؟',
'Slow down and give them ample space | Repeatedly sound the horn | Accelerate very close past them | Maintain speed regardless || Yavaşlayıp bol alan bırakın | Sürekli korna çalın | Çok yakınından hızlanarak geçin | Her durumda hızı koruyun || Vertraag en geef veel ruimte | Claxonneer herhaaldelijk | Versnel er vlak langs | Houd altijd dezelfde snelheid || تخفف السرعة وتترك مساحة كبيرة | تطلق البوق مرارًا | تسرع ملاصقًا لها | تحافظ على السرعة مهما حدث')
number(c,'s23','What is the maximum gap between the towing vehicle’s rear and the towed vehicle’s front? || Çeken aracın arkasıyla çekilen aracın önü arasında azami mesafe nedir? || Wat is de maximale afstand tussen de achterkant van het trekkende en de voorkant van het gesleepte voertuig? || ما أقصى مسافة بين مؤخرة المركبة القاطرة ومقدمة المركبة المقطورة؟','5 m | 2 m | 3 m | 10 m')
q(c,'s24','You leave a parking space while a pedestrian and cyclist approach your path. Who do you yield to? || Park yerinden çıkarken yaya ve bisikletli yolunuza yaklaşıyor. Kime yol verirsiniz? || U rijdt uit een parkeerplaats terwijl een voetganger en fietser uw pad naderen. Wie laat u voorgaan? || تخرج من موقف ومشاة ودرّاج يقتربان من مسارك. لمن تفسح؟',
'Both | Only the cyclist | Only the pedestrian | Neither if you indicated || İkisine de | Yalnızca bisikletliye | Yalnızca yayaya | Sinyal verdiyseniz hiçbirine || Beiden | Alleen de fietser | Alleen de voetganger | Niemand als u richting aangaf || لكليهما | للدرّاج فقط | للمشاة فقط | لا أحد إذا أشرت')
number(c,'s26','If used, approximately how far toward approaching traffic should a warning triangle be placed from the vehicle? || Kullanılıyorsa uyarı üçgeni yaklaşan trafik yönünde araçtan yaklaşık ne kadar uzağa konur? || Op ongeveer welke afstand richting naderend verkeer plaatst u een gevarendriehoek als u die gebruikt? || عند استخدام مثلث التحذير، على أي مسافة تقريبية من المركبة باتجاه المرور المقترب يُوضع؟','30 m | 5 m | 10 m | 100 m')
number(c,'s27','Below what height must children generally use an approved child restraint? || Çocuklar genel olarak hangi boyun altında onaylı çocuk güvenlik sistemi kullanmalıdır? || Onder welke lengte moeten kinderen in beginsel een goedgekeurd kinderzitje gebruiken? || دون أي طول يجب عمومًا استخدام نظام تثبيت أطفال معتمد؟','1.35 m | 1.00 m | 1.20 m | 1.50 m')
q(c,'s27','A rear-facing child seat is fitted where there is a front airbag. What is required? || Ön hava yastığı olan koltuğa arkaya bakan çocuk koltuğu takılıyor. Ne gerekir? || Een achterwaarts kinderzitje komt op een plaats met frontairbag. Wat is vereist? || يُركّب مقعد طفل مواجه للخلف في مكان ذي وسادة هوائية أمامية. ما المطلوب؟',
'Deactivate that airbag | Keep it active | Move the child seat closer to the dashboard | Use no restraint || O hava yastığını devre dışı bırakmak | Aktif tutmak | Çocuk koltuğunu ön panele yaklaştırmak | Güvenlik sistemi kullanmamak || Schakel die airbag uit | Laat hem actief | Zet het zitje dichter bij het dashboard | Gebruik geen beveiliging || تعطيل تلك الوسادة الهوائية | إبقاؤها فعالة | تقريب مقعد الطفل من لوحة القيادة | عدم استخدام تثبيت')
q(c,'s28','Must snorfiets riders and passengers wear an approved helmet? || Snorfiets sürücüleri ve yolcuları onaylı kask takmalı mı? || Moeten snorfietsers en hun passagiers een goedgekeurde helm dragen? || هل يجب على سائقي snorfiets وركابهم ارتداء خوذة معتمدة؟',
'Yes | Only passengers | Only at night | Only outside built-up areas || Evet | Yalnızca yolcular | Yalnızca gece | Yalnızca yerleşim dışında || Ja | Alleen passagiers | Alleen ’s nachts | Alleen buiten de bebouwde kom || نعم | الركاب فقط | ليلًا فقط | خارج المناطق المبنية فقط')
q(c,'s30','May a cyclist hold a phone to check navigation while riding? || Bisikletli sürerken navigasyon için telefonu elinde tutabilir mi? || Mag een fietser tijdens het rijden een telefoon vasthouden voor navigatie? || هل يجوز لدرّاج إمساك الهاتف للتحقق من الملاحة أثناء السير؟',
'No, the handheld-device prohibition also applies to cyclists | Yes, if not calling | Yes, at low speed | Yes, on every cycle path || Hayır, elde cihaz tutma yasağı bisikletlilere de uygulanır | Evet, arama yapmıyorsa | Evet, düşük hızda | Evet, her bisiklet yolunda || Nee, het vasthoudverbod geldt ook voor fietsers | Ja, zonder bellen | Ja, bij lage snelheid | Ja, op elk fietspad || لا، حظر إمساك الجهاز يشمل الدراجين | نعم دون اتصال | نعم بسرعة منخفضة | نعم على كل مسار دراجات')
c='traffic-rules'
q(c,'s1','Where must an ordinary cyclist ride when a mandatory cycle path is available? || Zorunlu bisiklet yolu varsa normal bisikletli nerede sürmelidir? || Waar moet een gewone fietser rijden als een verplicht fietspad aanwezig is? || أين يجب أن يسير راكب دراجة عادية عند وجود مسار إلزامي للدراجات؟',
'On the mandatory cycle path | On the pavement | Always on the carriageway | On the verge || Zorunlu bisiklet yolunda | Kaldırımda | Daima taşıt yolunda | Bankette || Op het verplichte fietspad | Op het trottoir | Altijd op de rijbaan | In de berm || على مسار الدراجات الإلزامي | على الرصيف | دائمًا على مسار المركبات | على الحافة')
q(c,'s5','You come from an unpaved road and a car approaches on a paved road from the left. Who gives way? || Siz kaplamasız yoldan, otomobil soldaki kaplamalı yoldan geliyor. Kim yol verir? || U komt van een onverharde weg en een auto komt van links op een verharde weg. Wie verleent voorrang? || تأتي من طريق غير معبد وسيارة من يسارك على طريق معبد. من يعطي الأولوية؟',
'You give way to the car on the paved road | The car always gives way to you | The faster vehicle has priority | The newest car has priority || Kaplamalı yoldaki otomobile siz yol verirsiniz | Otomobil size daima yol verir | Hızlı araç önceliklidir | Yeni otomobil önceliklidir || U laat de auto op de verharde weg voor | Die auto laat u altijd voor | Het snelste voertuig heeft voorrang | De nieuwste auto heeft voorrang || أنت تفسح للسيارة على الطريق المعبد | السيارة تفسح لك دائمًا | المركبة الأسرع لها الأولوية | السيارة الأحدث لها الأولوية')
q(c,'s5','A railway crossing is open but there is no room beyond it for your whole car. What do you do? || Hemzemin geçit açık ama ötesinde otomobilinizin tamamına yer yok. Ne yaparsınız? || De overweg is open, maar erachter past uw auto niet helemaal. Wat doet u? || معبر السكك مفتوح لكن لا توجد مساحة بعده لكل سيارتك. ماذا تفعل؟',
'Wait before the crossing until you can clear it | Enter and wait on the rails | Cross if no train is visible | Enter with hazard lights || Tamamen geçebileceğiniz zamana kadar önünde bekleyin | Girip raylarda bekleyin | Tren görünmüyorsa geçin | Dörtlülerle girin || Wacht vóór de overweg tot u hem kunt vrijmaken | Rijd op en wacht op de rails | Rijd op als geen trein zichtbaar is | Rijd op met alarmlichten || تنتظر قبل المعبر حتى تستطيع إخلاءه | تدخل وتنتظر على القضبان | تعبر إذا لم تر قطارًا | تدخل بأضواء التحذير')
q(c,'s7','When must you signal a turn? || Dönüş sinyali ne zaman verilmelidir? || Wanneer geeft u richting aan bij afslaan? || متى تعطي إشارة الانعطاف؟',
'Before starting the turn | Only after turning | Halfway through every turn | Only if another driver sounds the horn || Dönüşe başlamadan önce | Yalnızca dönüşten sonra | Her dönüşün ortasında | Yalnızca başka sürücü korna çalarsa || Vóór het afslaan | Alleen erna | Halverwege elke bocht | Alleen als iemand claxonneert || قبل بدء الانعطاف | بعده فقط | في منتصف كل انعطاف | فقط إذا أطلق سائق آخر البوق')
q(c,'s9','Which brief activity is an exception to the bus-stop stopping restriction described here? || Buradaki otobüs durağı durma yasağının kısa süreli istisnası nedir? || Welke korte handeling is hier een uitzondering op het stopverbod bij een bushalte? || ما النشاط القصير المستثنى هنا من منع التوقف عند موقف الحافلات؟',
'Immediately boarding or alighting passengers | Waiting for someone still at home | Shopping | Parking to read messages || Yolcunun hemen binmesi veya inmesi | Hâlâ evdeki birini beklemek | Alışveriş | Mesaj okumak için park || Onmiddellijk laten in- of uitstappen | Wachten op iemand die nog thuis is | Winkelen | Parkeren om berichten te lezen || صعود الركاب أو نزولهم فورًا | انتظار شخص لا يزال في المنزل | التسوق | الوقوف لقراءة الرسائل')
q(c,'s10','What must a required blue-zone parking disc show? || Mavi bölgede gereken park diski neyi göstermeli? || Wat moet een vereiste parkeerschijf in een blauwe zone tonen? || ماذا يجب أن يُظهر قرص الوقوف المطلوب في المنطقة الزرقاء؟',
'The arrival time | Only the planned departure time | The driver’s birthday | The vehicle’s speed || Varış saatini | Yalnızca planlanan çıkış saatini | Sürücünün doğum gününü | Aracın hızını || De aankomsttijd | Alleen de geplande vertrektijd | De verjaardag van de bestuurder | De voertuigsnelheid || وقت الوصول | وقت المغادرة المخطط فقط | ميلاد السائق | سرعة المركبة')
q(c,'s11','How must parked bicycles and mopeds be placed? || Park edilen bisiklet ve mopedler nasıl yerleştirilmeli? || Hoe moeten geparkeerde fietsen en bromfietsen staan? || كيف توضع الدراجات والموبيدات المتوقفة؟',
'Without obstructing other road users | Across the footpath | Across a cycle path | Wherever the rider finds shade || Diğer yol kullanıcılarını engellemeden | Yaya yolunu kapatarak | Bisiklet yolunu kapatarak | Sürücü nerede gölge bulursa || Zonder andere weggebruikers te hinderen | Dwars over het voetpad | Dwars over het fietspad | Waar de berijder schaduw vindt || دون إعاقة مستخدمي الطريق الآخرين | عبر ممر المشاة | عبر مسار الدراجات | حيث يجد الراكب ظلًا')
q(c,'s13','Which front lighting must a motor vehicle use while driving at night? || Motorlu araç gece sürerken hangi ön aydınlatmayı kullanmalı? || Welke verlichting voor moet een motorvoertuig ’s nachts tijdens het rijden gebruiken? || ما الإضاءة الأمامية المطلوبة للمركبة الآلية أثناء القيادة ليلًا؟',
'Dipped headlights | Daytime running lights alone | Parking lights alone | No lights on illuminated roads || Kısa farlar | Yalnızca gündüz farları | Yalnızca park lambaları | Aydınlık yolda lambasız || Dimlicht | Alleen dagrijlicht | Alleen stadslicht | Geen licht op verlichte wegen || المصابيح المنخفضة | أضواء النهار وحدها | أضواء الوقوف وحدها | بلا أضواء في الطرق المضاءة')
q(c,'s13','Which lights must a bicycle show at night? || Bisiklet gece hangi ışıkları göstermeli? || Welke lichten moet een fiets ’s nachts voeren? || ما الأضواء التي يجب أن تُظهرها الدراجة ليلًا؟',
'Steady white or yellow front light and steady red rear light | Red front and white rear | Flashing lights only | A front light only || Sabit beyaz veya sarı ön, sabit kırmızı arka ışık | Kırmızı ön ve beyaz arka | Yalnızca yanıp sönen ışıklar | Yalnızca ön ışık || Vast wit of geel voorlicht en vast rood achterlicht | Rood voor en wit achter | Alleen knipperlichten | Alleen een voorlicht || ضوء أبيض أو أصفر ثابت أمامًا وأحمر ثابت خلفًا | أحمر أمامًا وأبيض خلفًا | أضواء وامضة فقط | ضوء أمامي فقط')
q(c,'s14','A motor vehicle is stationary at night on the carriageway outside a built-up area. What lighting is required? || Motorlu araç gece yerleşim dışında taşıt yolunda duruyor. Hangi ışık gerekir? || Een motorvoertuig staat ’s nachts op de rijbaan buiten de bebouwde kom. Welke verlichting is nodig? || مركبة آلية متوقفة ليلًا على مسار المركبات خارج المنطقة المبنية. ما الإضاءة المطلوبة؟',
'Prescribed front and rear parking/position lights | Only an interior light | No lights if the engine is off | High beam only || Öngörülen ön ve arka park/konum lambaları | Yalnızca iç lamba | Motor kapalıysa ışık gerekmez | Yalnızca uzun far || Voorgeschreven stads- en achterlichten | Alleen binnenverlichting | Geen licht bij uitgeschakelde motor | Alleen grootlicht || أضواء الوقوف أو الموضع الأمامية والخلفية المقررة | ضوء داخلي فقط | لا أضواء والمحرك مطفأ | الضوء العالي فقط')
q(c,'s15','What does a green flashing light identify during authorised emergency operations? || Yetkili acil operasyonda yeşil yanıp sönen ışık neyi tanımlar? || Wat geeft groen knipperlicht bij bevoegde hulpverleningsoperaties aan? || ماذا يحدد الضوء الأخضر الومّاض في عمليات طوارئ مخولة؟',
'A command function, not priority by itself | Automatic priority over everyone | A private doctor’s unlimited rights | An open lane || Komuta görevini; tek başına geçiş üstünlüğü değil | Herkese karşı otomatik üstünlük | Özel doktorun sınırsız haklarını | Açık şeridi || Een commandofunctie, op zichzelf geen voorrang | Automatische voorrang boven iedereen | Onbeperkte rechten van een privéarts | Een open rijstrook || وظيفة قيادة، لا أولوية بذاته | أولوية تلقائية على الجميع | حقوق طبيب خاص بلا حدود | مسار مفتوح')
number(c,'s16','What minimum construction-related speed capability is specified for an autoweg? || Autoweg için yapısal olarak en az hangi hız yeteneği belirtilir? || Welke minimale constructiegerelateerde snelheid geldt voor toegang tot een autoweg? || ما أدنى قدرة سرعة تصميمية محددة لدخول autoweg؟','50 km/h | 25 km/h | 45 km/h | 60 km/h')
q(c,'s16','You miss a motorway exit. May you reverse to reach it? || Otoyol çıkışını kaçırdınız. Ulaşmak için geri gidebilir misiniz? || U mist een snelwegafrit. Mag u er achteruit naartoe? || فاتك مخرج الطريق السريع. هل ترجع للخلف للوصول إليه؟',
'No, reversing is prohibited | Yes, on the shoulder | Yes, with hazard lights | Yes, if close enough || Hayır, geri gitmek yasaktır | Evet, emniyet şeridinde | Evet, dörtlülerle | Evet, yeterince yakınsa || Nee, achteruitrijden is verboden | Ja, op de vluchtstrook | Ja, met alarmlichten | Ja, als het dichtbij is || لا، الرجوع ممنوع | نعم على كتف الطريق | نعم بأضواء التحذير | نعم إذا كان قريبًا')
q(c,'s16','An electronic red cross appears above a rush-hour lane. What does it mean? || Ek yoğunluk şeridinin üzerinde elektronik kırmızı çarpı var. Anlamı nedir? || Boven een spitsstrook verschijnt een rood kruis. Wat betekent dat? || تظهر علامة حمراء متقاطعة فوق مسار ساعات الذروة. ما معناها؟',
'The lane is closed | Overtaking is compulsory | The lane is open to all | Only a lower speed applies || Şerit kapalıdır | Sollama zorunludur | Şerit herkese açıktır | Yalnızca düşük hız geçerlidir || De strook is gesloten | Inhalen is verplicht | De strook is voor iedereen open | Alleen een lagere snelheid geldt || المسار مغلق | التجاوز إلزامي | المسار مفتوح للجميع | يسري حد سرعة أقل فقط')
q(c,'s20','An emergency ambulance approaches with blue light and siren. How should you react? || Ambulans acil görevde mavi ışık ve sirenle yaklaşıyor. Nasıl tepki vermelisiniz? || Een ambulance nadert met blauw licht en sirene bij een spoedrit. Hoe reageert u? || تقترب سيارة إسعاف في طوارئ بضوء أزرق وصفارة. كيف تتصرف؟',
'Make way promptly and safely, stopping if necessary | Always run a red light | Block its path and stop | Accelerate to stay ahead || Gerekirse durarak hızla ve güvenle yol açın | Her zaman kırmızıdan geçin | Yolunu kapatıp durun | Önünde kalmak için hızlanın || Maak vlot en veilig ruimte, stop zo nodig | Rijd altijd door rood | Blokkeer de route en stop | Versnel om ervoor te blijven || تفسح بسرعة وأمان وتتوقف عند الحاجة | تتجاوز الأحمر دائمًا | تسد طريقها وتتوقف | تسرع لتبقى أمامها')
q(c,'s26','Hazard lights are operating on an obstructing stationary vehicle. Is a warning triangle also required? || Engelleyici duran araçta dörtlüler çalışıyor. Üçgen de gerekli mi? || De alarmlichten van een hinderlijk stilstaand voertuig werken. Is ook een gevarendriehoek verplicht? || أضواء التحذير تعمل على مركبة متوقفة تشكل عائقًا. هل يلزم مثلث أيضًا؟',
'No, not when the hazard lights are operating | Yes, always | Only at noon | Only in built-up areas || Hayır, dörtlüler çalışırken gerekmez | Evet, daima | Yalnızca öğlen | Yalnızca yerleşim içinde || Nee, niet als de alarmlichten werken | Ja, altijd | Alleen ’s middags | Alleen binnen de bebouwde kom || لا، ليس عند عمل أضواء التحذير | نعم دائمًا | ظهرًا فقط | داخل المناطق المبنية فقط')
q(c,'s26a','May a passenger travel in the boot of an ordinary car? || Normal otomobilin bagajında yolcu taşınabilir mi? || Mag een passagier in de kofferbak van een gewone auto reizen? || هل يجوز لراكب السفر في صندوق سيارة عادية؟',
'No, passengers must use designated seats | Yes, for short trips | Yes, below 30 km/h | Yes, if all seats are full || Hayır, yolcular belirlenmiş koltukları kullanmalı | Evet, kısa yolda | Evet, 30 km/sa altında | Evet, tüm koltuklar doluysa || Nee, passagiers gebruiken bestemde zitplaatsen | Ja, bij korte ritten | Ja, onder 30 km/h | Ja, als alle stoelen bezet zijn || لا، يستخدم الركاب المقاعد المخصصة | نعم للرحلات القصيرة | نعم دون 30 كم/س | نعم إذا امتلأت المقاعد')
q(c,'s27','How should the shoulder part of a seatbelt be worn? || Emniyet kemerinin omuz bölümü nasıl takılmalıdır? || Hoe moet het schouderdeel van de gordel worden gedragen? || كيف يُلبس الجزء الكتفي من حزام الأمان؟',
'Across the shoulder and chest | Under the arm | Behind the back | Loosely over the seat only || Omuz ve göğüs üzerinden | Kol altından | Sırt arkasından | Yalnızca koltuğun üzerinden gevşekçe || Over schouder en borst | Onder de arm | Achter de rug | Los over alleen de stoel || عبر الكتف والصدر | تحت الذراع | خلف الظهر | مرتخيًا فوق المقعد فقط')
q(c,'s29','What support does a child under 8 need when carried on a bicycle? || Bisiklette taşınan 8 yaş altı çocuk için hangi destek gerekir? || Welke steun heeft een kind onder 8 nodig bij vervoer op een fiets? || ما الدعم المطلوب لطفل دون 8 سنوات يُنقل على دراجة؟',
'Support for back, hands and feet | Only a cushion | No support if holding the rider | Foot support alone || Sırt, eller ve ayaklar için destek | Yalnızca minder | Sürücüyü tutuyorsa destek gerekmez | Yalnızca ayak desteği || Steun voor rug, handen en voeten | Alleen een kussen | Geen steun bij vasthouden van de berijder | Alleen voetsteun || دعم للظهر واليدين والقدمين | وسادة فقط | لا دعم إذا أمسك بالسائق | دعم القدمين فقط')
q(c,'s30','When is using a securely mounted phone permitted in principle? || Sabitlenmiş telefonun kullanımı ilke olarak ne zaman izinlidir? || Wanneer is gebruik van een stevig gemonteerde telefoon in beginsel toegestaan? || متى يُسمح مبدئيًا باستخدام هاتف مثبت بإحكام؟',
'When not held and without danger or obstruction | Whenever the driver wants | Only when held in one hand | Whenever the screen is large || Elde tutulmadan, tehlike veya engel yaratmadan | Sürücü istediği zaman | Yalnızca tek elde tutulduğunda | Ekran büyük olduğunda || Zonder vasthouden en zonder gevaar of hinder | Wanneer de bestuurder wil | Alleen in één hand | Bij een groot scherm || دون إمساكه ودون خطر أو إعاقة | متى أراد السائق | عند إمساكه بيد واحدة فقط | كلما كانت الشاشة كبيرة')
