#!/usr/bin/env node
/**
 * inject-seo.js
 * ExamTheorie — Otomatik SEO tag enjeksiyonu
 *
 * Ne yapar:
 *  1. Repo kökündeki tüm .html dosyalarını tarar
 *  2. Her dosyanın dilini ve "slug"ını dosya adından çıkarır
 *  3. seo-config.json'dan meta description okur (varsa)
 *  4. <head> içine şunları ekler/günceller:
 *       - <meta name="description">
 *       - <link rel="canonical">
 *       - hreflang alternate linkleri (4 dil)
 *       - <meta name="robots">
 *       - Open Graph tagları
 *
 * Kullanım:
 *   node inject-seo.js [--dry-run] [--dir ./path]
 */

const fs   = require('fs');
const path = require('path');

// ── Ayarlar ──────────────────────────────────────────────────────────────────

const BASE_URL   = 'https://examtheorie.nl';
const SITE_NAME  = 'ExamTheorie';

// Dil eşleştirme: dosya adı prefiksi → HTML lang + hreflang kodu
const LANG_MAP = {
  'tr-' : { lang: 'tr', hreflang: 'tr' },
  'nl-' : { lang: 'nl', hreflang: 'nl' },
  'ar-' : { lang: 'ar', hreflang: 'ar' },
  ''    : { lang: 'en', hreflang: 'en' },   // prefiks yoksa İngilizce
};

// Dil prefikslerini slug'dan temizlerken kullanılacak sıra (uzundan kısaya)
const LANG_PREFIXES = ['tr-', 'nl-', 'ar-'];

// Atlanacak dosya kalıpları (regex — dosya adına göre)
const SKIP_PATTERNS = [
  /^test-\d+/,          // quiz dosyaları: test-1-en.html
  /^ru-/,               // Rusça (aktif değil)
  /^fa-/,               // Farsça (aktif değil)
  /^deneme/,            // geliştirme dosyaları
  /^sayfa/,
  /^deney/,
  /^arapdugmeler/,
];



// ── CLI argümanları ───────────────────────────────────────────────────────────

const args    = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const DIR_IDX = args.indexOf('--dir');
const ROOT    = DIR_IDX !== -1 ? path.resolve(args[DIR_IDX + 1]) : process.cwd();

// ── Config yükle ─────────────────────────────────────────────────────────────

const CONFIG_PATH = path.join(ROOT, 'seo-config.json');
let config = {};
if (fs.existsSync(CONFIG_PATH)) {
  try {
    config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    console.log(`✅ seo-config.json yüklendi (${Object.keys(config).length} kayıt)`);
  } catch (e) {
    console.warn('⚠️  seo-config.json parse hatası:', e.message);
  }
} else {
  console.log('ℹ️  seo-config.json bulunamadı — description\'lar boş bırakılacak');
}

// ── Yardımcı fonksiyonlar ─────────────────────────────────────────────────────

/** Dosya adından dil ve slug bilgisini çıkarır */
function parseFilename(filename) {
  const base = path.basename(filename, '.html');

  // Dil tespiti
  let langKey = '';
  let slug    = base;
  for (const prefix of LANG_PREFIXES) {
    if (base.startsWith(prefix)) {
      langKey = prefix;
      slug    = base.slice(prefix.length);
      break;
    }
  }

  // quiz dosyası mı? (test-1-nl.html gibi)
  const isQuiz = /^test-\d+/.test(slug);

  return {
    lang    : LANG_MAP[langKey],
    langKey,
    slug,
    isQuiz,
    base,
  };
}

/** Bu slug için diğer dil versiyonlarının URL'lerini üretir */
function buildHreflangs(slug) {
  return {
    en: `${BASE_URL}/${slug}`,
    tr: `${BASE_URL}/tr-${slug}`,
    nl: `${BASE_URL}/nl-${slug}`,
    ar: `${BASE_URL}/ar-${slug}`,
  };
}

/** Config'den description çeker */
function getDescription(slug, langCode) {
  const entry = config[slug];
  if (!entry) return '';
  return (entry[langCode] && entry[langCode].description) || entry.description || '';
}

/** SEO bloğunu oluşturur — mevcut varsa günceller */
function buildSeoBlock(slug, langInfo, htmlTitle) {
  const langCode   = langInfo.hreflang;
  const canonical  = langCode === 'en'
    ? `${BASE_URL}/${slug}`
    : `${BASE_URL}/${langInfo.hreflang}-${slug}`;
  const hreflangs  = buildHreflangs(slug);
  const desc       = getDescription(slug, langCode);
  const ogTitle    = htmlTitle || `${slug.replace(/-/g, ' ')} – ${SITE_NAME}`;

  const descTag    = desc
    ? `    <meta name="description" content="${desc}" />`
    : `    <!-- TODO: meta description for ${slug} (${langCode}) -->`;

  return `    <!-- ═══ SEO (auto-generated by inject-seo.js) ═══ -->
    <meta name="robots" content="index, follow" />
${descTag}
    <link rel="canonical" href="${canonical}" />
    <link rel="alternate" hreflang="en" href="${hreflangs.en}" />
    <link rel="alternate" hreflang="tr" href="${hreflangs.tr}" />
    <link rel="alternate" hreflang="nl" href="${hreflangs.nl}" />
    <link rel="alternate" hreflang="ar" href="${hreflangs.ar}" />
    <link rel="alternate" hreflang="x-default" href="${hreflangs.en}" />
    <meta property="og:title" content="${ogTitle}" />
    <meta property="og:description" content="${desc}" />
    <meta property="og:url" content="${canonical}" />
    <meta property="og:site_name" content="${SITE_NAME}" />
    <meta property="og:type" content="article" />
    <!-- ═══ /SEO ═══ -->`;
}

/** HTML dosyasını işler */
function processFile(filepath) {
  const filename = path.basename(filepath);
  const { lang, slug, isQuiz, base } = parseFilename(filename);

  // Skip kontrolü
  for (const pat of SKIP_PATTERNS) {
    if (pat.test(filename)) {
      console.log(`  ⏭  Atlandı: ${filename}`);
      return false;
    }
  }
  if (!lang) {
    console.log(`  ⏭  Atlandı (dil tanınamadı): ${filename}`);
    return false;
  }

  let html = fs.readFileSync(filepath, 'utf8');

  // Başlığı al
  const titleMatch = html.match(/<title>([^<]*)<\/title>/i);
  const htmlTitle  = titleMatch ? titleMatch[1].trim() : '';

  const seoBlock = buildSeoBlock(slug, lang, htmlTitle);

  // Mevcut SEO bloğu var mı?
  if (html.includes('auto-generated by inject-seo.js')) {
    // Güncelle
    html = html.replace(
      /[ \t]*<!-- ═══ SEO \(auto-generated[\s\S]*?═══ \/SEO ═══ -->/,
      seoBlock
    );
    console.log(`  🔄 Güncellendi: ${filename}`);
  } else {
    // <head> içine, <title>'dan hemen sonra ekle
    if (html.includes('</title>')) {
      html = html.replace('</title>', `</title>\n${seoBlock}`);
    } else if (html.includes('<head>')) {
      html = html.replace('<head>', `<head>\n${seoBlock}`);
    } else {
      console.warn(`  ⚠️  <head> bulunamadı: ${filename}`);
      return false;
    }
    console.log(`  ✅ Eklendi: ${filename} (${lang.hreflang})`);
  }

  if (!DRY_RUN) {
    fs.writeFileSync(filepath, html, 'utf8');
  }
  return true;
}

// ── HTML dosyalarını tara ─────────────────────────────────────────────────────

function scanDir(dir) {
  const results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (['node_modules', '.git', '.github'].includes(entry.name)) continue;
      results.push(...scanDir(path.join(dir, entry.name)));
    } else if (entry.isFile() && entry.name.endsWith('.html')) {
      results.push(path.join(dir, entry.name));
    }
  }
  return results;
}

// ── Ana çalıştırma ────────────────────────────────────────────────────────────

console.log(`\n🚀 ExamTheorie SEO Injector`);
console.log(`📁 Dizin : ${ROOT}`);
console.log(`${DRY_RUN ? '🔍 MOD    : DRY RUN (dosya yazılmaz)' : '✍️  MOD    : YAZMA aktif'}\n`);

const files   = scanDir(ROOT);
console.log(`📄 Bulunan HTML dosyası: ${files.length}\n`);

let processed = 0;
let skipped   = 0;

for (const file of files) {
  const ok = processFile(file);
  if (ok) processed++; else skipped++;
}

console.log(`\n🏁 Tamamlandı: ${processed} işlendi, ${skipped} atlandı`);
if (DRY_RUN) console.log('   (DRY RUN — hiçbir dosya değiştirilmedi)');
