#!/usr/bin/env node
/**
 * inject-seo.js
 * ExamTheorie — Otomatik SEO tag enjeksiyonu
 *
 * Ne yapar:
 *  1. Repo kökündeki tüm .html dosyalarını tarar
 *  2. Her dosyanın dilini ve "slug"ını dosya adından çıkarır
 *  3. seo-config.json'dan meta description okur (varsa)
 *  4. <head> içine şunları ekler/günceller:
 *       - <meta name="description">
 *       - <link rel="canonical">
 *       - hreflang alternate linkleri (yalnızca mevcut dil dosyaları)
 *       - <meta name="robots">
 *       - Open Graph tagları
 *
 * Kullanım:
 *   node inject-seo.js [--dry-run] [--dir ./path]
 */

const fs   = require('fs');
const path = require('path');

// ── Ayarlar ──────────────────────────────────────────────────────────────────

const BASE_URL   = 'https://examtheorie.nl';
const SITE_NAME  = 'ExamTheorie';

// Dil eşleştirme: dosya adı prefiksi → HTML lang + hreflang kodu
const LANG_MAP = {
  'tr-' : { lang: 'tr', hreflang: 'tr' },
  'nl-' : { lang: 'nl', hreflang: 'nl' },
  'ar-' : { lang: 'ar', hreflang: 'ar' },
  ''    : { lang: 'en', hreflang: 'en' },   // prefiks yoksa İngilizce
};

// Dil prefikslerini slug'dan temizlerken kullanılacak sıra
const LANG_PREFIXES = ['tr-', 'nl-', 'ar-'];

// Atlanacak dosya kalıpları
const SKIP_PATTERNS = [
  /^test-\d+/,          // quiz dosyaları: test-1-en.html
  /^ru-/,              // Rusça (aktif değil)
  /^fa-/,              // Farsça (aktif değil)
  /^deneme/,           // geliştirme dosyaları
  /^sayfa/,
  /^deney/,
  /^arapdugmeler/,
];

// ── CLI argümanları ──────────────────────────────────────────────────────────

const args    = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const DIR_IDX = args.indexOf('--dir');
const ROOT    = DIR_IDX !== -1
  ? path.resolve(args[DIR_IDX + 1])
  : process.cwd();

// ── Config yükle ─────────────────────────────────────────────────────────────

const CONFIG_PATH = path.join(ROOT, 'seo-config.json');
let config = {};

if (fs.existsSync(CONFIG_PATH)) {
  try {
    config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    console.log(
      `✅ seo-config.json yüklendi (${Object.keys(config).length} kayıt)`
    );
  } catch (e) {
    console.warn('⚠️ seo-config.json parse hatası:', e.message);
  }
} else {
  console.log(
    'ℹ️ seo-config.json bulunamadı — description\'lar boş bırakılacak'
  );
}

// ── Yardımcı fonksiyonlar ─────────────────────────────────────────────────────

/** Dosya adından dil ve slug bilgisini çıkarır */
function parseFilename(filename) {
  const base = path.basename(filename, '.html');

  let langKey = '';
  let slug = base;

  for (const prefix of LANG_PREFIXES) {
    if (base.startsWith(prefix)) {
      langKey = prefix;
      slug = base.slice(prefix.length);
      break;
    }
  }

  const isQuiz = /^test-\d+/.test(slug);

  return {
    lang: LANG_MAP[langKey],
    langKey,
    slug,
    isQuiz,
    base,
  };
}

/** Ana sayfa kök URL kullanır; diğer kök sayfaların temiz URL düzeni korunur. */
function pageUrl(base) {
  return base === 'index'
    ? `${BASE_URL}/`
    : `${BASE_URL}/${base}`;
}

/** Yalnızca kök dizinde gerçekten bulunan dil dosyalarını bildirir. */
function buildHreflangs(slug) {
  const result = {};

  for (const [prefix, info] of Object.entries(LANG_MAP)) {
    const base = `${prefix}${slug}`;
    const candidate = path.join(ROOT, `${base}.html`);

    if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
      result[info.hreflang] = pageUrl(base);
    }
  }

  return result;
}

/** Config'den description çeker */
function getDescription(slug, langCode) {
  const entry = config[slug];

  if (!entry) return '';

  return (
    (entry[langCode] && entry[langCode].description)
    || entry.description
    || ''
  );
}

/** SEO bloğunu oluşturur */
function buildSeoBlock(slug, langInfo, htmlTitle) {
  const langCode = langInfo.hreflang;
  const canonical = pageUrl(
    langCode === 'en' ? slug : `${langCode}-${slug}`
  );

  const hreflangs = buildHreflangs(slug);
  const alternates = Object.entries(hreflangs);

  // Tek URL içinde değişen diller için ayrı dil URL'leri ilan edilmez.
  const alternateTags = alternates.length > 1
    ? alternates.map(([code, url]) =>
        `    <link rel="alternate" hreflang="${code}" href="${url}" />`
      ).concat(
        hreflangs.en
          ? [
              `    <link rel="alternate" hreflang="x-default" href="${hreflangs.en}" />`
            ]
          : []
      ).join('\n') + '\n'
    : '';

  const desc = getDescription(slug, langCode);
  const ogTitle = htmlTitle
    || `${slug.replace(/-/g, ' ')} – ${SITE_NAME}`;

  const descTag = desc
    ? `    <meta name="description" content="${desc}" />`
    : `    <!-- TODO: meta description for ${slug} (${langCode}) -->`;

  return `    <!-- ═══ SEO (auto-generated by inject-seo.js) ═══ -->
    <meta name="robots" content="index, follow" />
${descTag}
    <link rel="canonical" href="${canonical}" />
${alternateTags}    <meta property="og:title" content="${ogTitle}" />
    <meta property="og:description" content="${desc}" />
    <meta property="og:url" content="${canonical}" />
    <meta property="og:site_name" content="${SITE_NAME}" />
    <meta property="og:type" content="article" />
    <!-- ═══ /SEO ═══ -->`;
}

/** HTML dosyasını işler */
function processFile(filepath) {
  const filename = path.basename(filepath);
  const { lang, slug } = parseFilename(filename);

  for (const pat of SKIP_PATTERNS) {
    if (pat.test(filename)) {
      console.log(`  ⏭ Atlandı: ${filename}`);
      return false;
    }
  }

  if (!lang) {
    console.log(`  ⏭ Atlandı (dil tanınamadı): ${filename}`);
    return false;
  }

  let html = fs.readFileSync(filepath, 'utf8');

  const titleMatch = html.match(/<title>([^<]*)<\/title>/i);
  const htmlTitle = titleMatch ? titleMatch[1].trim() : '';

  const seoBlock = buildSeoBlock(slug, lang, htmlTitle);

  if (html.includes('auto-generated by inject-seo.js')) {
    html = html.replace(
      /[ \t]*<!-- ═══ SEO \(auto-generated[\s\S]*?═══ \/SEO ═══ -->/,
      seoBlock
    );

    console.log(`  🔄 Güncellendi: ${filename}`);
  } else {
    if (html.includes('</title>')) {
      html = html.replace('</title>', `</title>\n${seoBlock}`);
    } else if (html.includes('<head>')) {
      html = html.replace('<head>', `<head>\n${seoBlock}`);
    } else {
      console.warn(`  ⚠️ <head> bulunamadı: ${filename}`);
      return false;
    }

    console.log(`  ✅ Eklendi: ${filename} (${lang.hreflang})`);
  }

  if (!DRY_RUN) {
    fs.writeFileSync(filepath, html, 'utf8');
  }

  return true;
}

// ── HTML dosyalarını tara ─────────────────────────────────────────────────────

function scanDir(dir) {
  const results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    // Bu betiğin dil ve temiz URL kuralları yalnızca kök HTML dosyaları içindir.
    // theory/en/... gibi alt dizinlerin farklı URL yapısını değiştirme.
    if (entry.isFile() && entry.name.endsWith('.html')) {
      results.push(path.join(dir, entry.name));
    }
  }

  return results;
}

// ── Ana çalıştırma ────────────────────────────────────────────────────────────

console.log('\n🚀 ExamTheorie SEO Injector');
console.log(`📁 Dizin: ${ROOT}`);
console.log(
  `${DRY_RUN
    ? '🔍 MOD: DRY RUN (dosya yazılmaz)'
    : '✍️ MOD: YAZMA aktif'}\n`
);

const files = scanDir(ROOT);
console.log(`📄 Bulunan HTML dosyası: ${files.length}\n`);

let processed = 0;
let skipped = 0;

for (const file of files) {
  const ok = processFile(file);

  if (ok) {
    processed++;
  } else {
    skipped++;
  }
}

console.log(
  `\n🏁 Tamamlandı: ${processed} işlendi, ${skipped} atlandı`
);

if (DRY_RUN) {
  console.log('   (DRY RUN — hiçbir dosya değiştirilmedi)');
}