name: Test Scriptlerini Guncelle
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Scriptini Calistir
        run: python update_scripts.py
      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Test dosyalari guncellendi" || echo "No changes"
          git push